nop()
inst	(0x0)
c6(0x7)
volume	(110)
vol_range	(3)
play	('A-4', far=True)
pause	(12)
play	('A-4')
pause	(12)
play	('A-4')
stop	('A-4')
stop	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('B-4')
stop	('B-4', pause=24)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
pause	(32)
stop	('A-4', pause=16)
pause	(32)
pause	(13)
vol_range	(2)
play	('G#4')
stop	('G#4', pause=3)
halt	()
halt	()
compress()
