; Collision map and bonus constants. These are often used together in the same data type
BOMB_UP         = 1
FIRE_UP         = 2
REMOTE_CONTROL  = 3
SPEED_UP        = 4
VEST            = 5
EXTRA_LIFE      = 6
BOMB_PASS       = 7
WALL_PASS       = 8
EXTRA_TIME      = 9
FULL_FIRE       = 0xA
RED_BOMBS       = 0xB
KICK            = 0xC
PUNCH           = 0xD
ONIGIRI         = 0xE
POISON          = 0xF
EXIT            = 0x10
HEART           = 0x11
CAKE            = 0x12
RANDOM          = 0x13
KENDAMA         = 0x14
APPLE           = 0x15
FIRE_EXT        = 0x16
POPSICLE        = 0x17
ICE_CREAM       = 0x18
BONUS_MASK      = 0x1F
BOMB            = 0x20
SOFT_BLOCK      = 0x40
HARD_BLOCK      = 0x80
BLAST           = 0x100
POTENTIAL_BLAST = 0x800
PLAYER          = 0x8000

; Tiles

TILE_SOFTBLOCK_SHADED  = 0x02
TILE_HARDBLOCK         = 0x04
TILE_SOFTBLOCK         = 0x06
TILE_EMPTY             = 0x08
TILE_EMPTY_SOFT_SHADED = 0x0A
TILE_EMPTY_HARD_SHADED = 0x0C

; A Palettes (Backgrounds)
HUD_PALETTE     = 0
PEACE_TOWN_PALETTE_1 = 1
PEACE_TOWN_PALETTE_2 = 2
PEACE_TOWN_PALETTE_3 = 3
BONUS_PALETTE_1 = 4
BONUS_PALETTE_2 = 5
PEACE_TOWN_BOMB_PALETTE = 6
PEACE_TOWN_FIRE_PALETTE = 7
VILLAGE_PALETTE_1 = 0xA
VILLAGE_PALETTE_2 = 0xB
VILLAGE_PALETTE_3 = 0xC
VILLAGE_BOMB_PALETTE = 0xD
VILLAGE_FIRE_PALETTE = 0xE
BACKGROUND_BLACK_PALETTE = 0xF
CASTLE_PALETTE_1 = 0x10
CASTLE_PALETTE_2 = 0x11
CASTLE_PALETTE_3 = 0x12
CASTLE_BOMB_PALETTE = 0x13
CASTLE_FIRE_PALETTE = 0x14
DOME_PALETTE_1  = 0x15
DOME_PALETTE_2  = 0x16
DOME_PALETTE_3  = 0x17
DOME_BOMB_PALETTE = 0x18
DOME_FIRE_PALETTE = 0x19
PARK_PALETTE_1  = 0x1A
PARK_PALETTE_2  = 0x1B
PARK_PALETTE_3  = 0x1C
PARK_BOMB_PALETTE = 0x1D
PARK_FIRE_PALETTE = 0x1E
CIRCUS_PALETTE_1 = 0x24
CIRCUS_PALETTE_2 = 0x25
CIRCUS_PALETTE_3 = 0x26
CIRCUS_BOMB_PALETTE = 0x27
CIRCUS_FIRE_PALETTE = 0x28
FACTORY_PALETTE_1 = 0x29
FACTORY_PALETTE_2 = 0x2A
FACTORY_PALETTE_3 = 0x2B
FACTORY_BOMB_PALETTE = 0x2C
FACTORY_FIRE_PALETTE = 0x2D
BACKGROUND_WHITE_PALETTE = 0x2E
ARENA_PALETTE_1 = 0x2F
ARENA_PALETTE_2 = 0x30
ARENA_PALETTE_3 = 0x31
ARENA_BOMB_PALETTE = 0x32
ARENA_FIRE_PALETTE = 0x33
CRANE_BG_PALETTE = 0x35
GARDEN_PALETTE_1 = 0x36
GARDEN_PALETTE_2 = 0x37
GARDEN_PALETTE_3 = 0x38
GARDEN_BOMB_PALETTE = 0x39
GARDEN_FIRE_PALETTE = 0x3A
POWER_ZONE_PALETTE_1 = 0x3B
POWER_ZONE_PALETTE_2 = 0x3C
POWER_ZONE_BOMB_PALETTE = 0x3D
POWER_ZONE_FIRE_PALETTE = 0x3E
CLOWN_MASK_SPOTLIGHT_PALETTE = 0x3F
DIAMOND_TOWER_PALETTE_1 = 0x40
DIAMOND_TOWER_PALETTE_2 = 0x41
DIAMOND_TOWER_BOMB_PALETTE = 0x42
DIAMOND_TOWER_FIRE_PALETTE = 0x43
SPEED_ZONE_PALETTE_1 = 0x44
SPEED_ZONE_PALETTE_2 = 0x45
SPEED_ZONE_PALETTE_3 = 0x46
SPEED_ZONE_BOMB_PALETTE = 0x47
SPEED_ZONE_FIRE_PALETTE = 0x48
NORMAL_ZONE_PALETTE = 0x49
NORMAL_ZONE_BOMB_PALETTE = 0x4A
NORMAL_ZONE_FIRE_PALETTE = 0x4B
WARP_ZONE_PALETTE_1 = 0x4C
WARP_ZONE_PALETTE_2 = 0x4D
WARP_ZONE_PALETTE_3 = 0x4E
WARP_ZONE_BOMB_PALETTE = 0x4F
WARP_ZONE_FIRE_PALETTE = 0x50
TUNNEL_ZONE_PALETTE_1 = 0x51
TUNNEL_ZONE_PALETTE_2 = 0x52
TUNNEL_ZONE_PALETTE_3 = 0x53
TUNNEL_ZONE_BOMB_PALETTE = 0x54
TUNNEL_ZONE_FIRE_PALETTE = 0x55
MAP_PALETTE_1   = 0x5B
MAP_PALETTE_2   = 0x5C
MAP_PALETTE_3   = 0x5D
DRAW_BG_PALETTE = 0x5E
VICTORY_YELLOW_BOMBERMAN_PALETTE = 0x60
VICTORY_ORANGE_BOMBERMAN_PALETTE = 0x61
VICTORY_BLUE_BOMBERMAN_PALETTE = 0x62
VICTORY_GREEN_BOMBERMAN_PALETTE = 0x63
VICTORY_MAGENTA_BOMBERMAN_PALETTE = 0x64
VICTORY_GRASS_PALETTE = 0x65
VICTORY_PURPLE_BOMBERMAN_PALETTE = 0x66
LOGO_PALETTE_1  = 0x67
LOGO_PALETTE_2  = 0x68
DOME_PALETTE_1_INVERT = 0x69
DOME_PALETTE_2_INVERT = 0x6A
DOME_PALETTE_3_INVERT = 0x6B
DOME_BOMB_PALETTE_INVERT = 0x6C
DOME_FIRE_PALETTE_INVERT = 0x6D
BONUS_1_INVERT_PALETTE = 0x6E
BONUS_2_INVERT_PALETTE = 0x6F
CONTINUE_PALETTE_1 = 0x71
CONTINUE_PALETTE_2 = 0x72
SPIDERER_BG_PALETTE_1 = 0x73
CREDITS_END_PALETTE = 0x74
SPIDERER_BG_PALETTE_2 = 0x75
SPIDERER_FIRE_BG_PALETTE_1 = 0x76
SPIDERER_FIRE_BG_PALETTE_2 = 0x78
SPIDERER_BG_PALETTE_3 = 0x79
GARDEN_PALETTE_3_COPY = 0x7A
CREDITS_SEPIA_PALETTE_1 = 0x7D
CREDITS_SEPIA_PALETTE_2 = 0x7F
CREDITS_SEPIA_PALETTE_3 = 0x80

; B Palettes (Sprites)
UNKNOWN         = 0
SPLASH_PALETTE  = 1
METAL_KUWAGEN_PALETTE = 2
KUWAGEN_PALETTE = 3
RED_BOMB_PALETTE = 4
SENSHIYAN_PALETTE = 5
SHIRO_PALETTE   = 6
KURO_PALETTE    = 7
AKA_PALETTE     = 8
AO_PALETTE      = 9
CUPPEN_PALETTE  = 0xA
PURPLE_BOMBERMAN_PALETTE = 0xB
BANEN_PALETTE   = 0xC
CLOWN_MASK_PALETTE_0 = 0xD
WHITE_PALETTE   = 0xE
BLACK_PALETTE   = 0xF
CLOWN_MASK_PALETTE_1 = 0x10
CLOWN_MASK_PALETTE_2 = 0x11
GENERIC_BOSS_FIRE_PALETTE = 0x12
MOOK_PALETTE    = 0x13
CRANE_PALETTE   = 0x14
ANZENDA_PALETTE = 0x15
MOGUCHAN_PALETTE_J = 0x17
PROPENE_PALETTE = 0x19
MOVING_PLATFORM_PALETTE = 0x1A
YOROISO_PALETTE = 0x1B
BIGARON_PALETTE_1 = 0x1F
BIGARON_PALETTE_2 = 0x20
BIGARON_FIRE_PALETTE = 0x21
MISSLE_PALETTE  = 0x23
MECHA_ONITA_PALETTE = 0x24
MECHA_ONITA_SHOCK_PALETTE = 0x25
SPIDERER_PALETTE_0 = 0x26
SPIDERER_PALETTE_1 = 0x27
SPIDERER_FIRE_PALETTE = 0x28
BOMB_PALETTE    = 0x29
KOURARU_PALETTE = 0x2A
UNKNOWN_FADING_PALETTE_0 = 0x2B
UNKNOWN_FADING_PALETTE_1 = 0x2C
UNKNOWN_FADING_PALETTE_2 = 0x2D
PAKUPA_PALETTE  = 0x2E
DOUKEN_PALETTE  = 0x2F
MECHA_BOMBER_WHITE_PALETTE = 0x30
MECHA_BOMBER_BLACK_PALETTE = 0x31
MECHA_BOMBER_RED_PALETTE = 0x32
MECHA_BOMBER_BLUE_PALETTE = 0x33
MECHA_BOMBER_GOLD_PALETTE = 0x34
MECHA_BOMBER_GREEN_PALETTE = 0x35
MECHA_BOMBER_MAGENTA_PALETTE = 0x36
MECHA_BOMBER_PURPLE_PALETTE = 0x37
EXPLOSIONS_PALETTE = 0x38
CARAT_DIAMOND_PALETTE = 0x39
DENGURIN_PALETTE = 0x3A
ROBOCOM_PALETTE = 0x3B
CHAMELEOMAN_PALETTE = 0x3C
OLD_MECHA_BOMBER_GOLD_PALETTE = 0x3D
OLD_KIERUN_PALETTE = 0x3E
MAIN_MENU_PALETTE = 0x3F
SCOREBOARD_PALETTE_0 = 0x40
BATTLE_SCREEN_ORANGE_PALETTE = 0x41
BATTLE_SCREEN_BLUE_PALETTE = 0x42
MOGUCHAN_PALETTE = 0x43
BAKUDA_PALETTE  = 0x44
KIERUN_PALETTE  = 0x45
GREEN_BOMB_PALETTE = 0x46
DIAMOND_TOWER_PALETTE = 0x47
WHITE_FALLING_PALETTE = 0x49
BLACK_FALLING_PALETTE = 0x4A
RED_FALLING_PALETTE = 0x4B
BLUE_FALLING_PALETTE = 0x4C
WHITE_VICTORY_PALETTE_0 = 0x4D
WHITE_VICTORY_PALETTE_1 = 0x4E
VICTORY_TEXT_PALETTE = 0x4F
BLACK_VICTORY_PALETTE_0 = 0x50
BLACK_VICTORY_PALETTE_1 = 0x51
RED_VICTORY_PALETTE_0 = 0x52
RED_VICTORY_PALETTE_1 = 0x53
BLUE_VICTORY_PALETTE_0 = 0x54
BLUE_VICTORY_PALETTE_1 = 0x55
BATTLE_SCREEN_RED_PALETTE = 0x56
BATTLE_SCREEN_GREEN_PALETTE = 0x57
TROPHY_SPARK_PALETTE = 0x58
INTRO_1_PALETTE = 0x5A
INTRO_2_PALETTE = 0x5B
INTRO_4_PALETTE = 0x5C
INTRO_3_PALETTE = 0x5D
INVERT_SHIRO    = 0x5E
INVERT_KURO     = 0x5F
INVERT_BOMB     = 0x60
INVERT_FIRE_BOMB = 0x61
INVERT_AKA      = 0x62
INVERT_AO       = 0x63
INVERT_BLACK    = 0x64
INVERT_WHITE    = 0x65
ONITA_FADE_PALETTE_1 = 0x66
ONITA_FADE_PALETTE_2 = 0x67
PASSWORD_DIGITS_PALETTE = 0x68
EMPTY_PALETTE   = 0x69
POISON_PALETTE  = 0x6A
INTRO_BALOON_PALETTE = 0x6B
INTRO_SHIP_PALETTE = 0x6C
OLD_STARNUTS_PALETTE = 0x6D
KEIBIN_PALETTE  = 0x6E
STARNUTS_PALETTE = 0x6F
METAL_PROPENE_PALETTE = 0x70
KINKARU_PALETTE = 0x71
METAL_U_PALETTE = 0x72
RED_BAKUDA_PALETTE = 0x73
ARENA_GATE_PALETTE = 0x74
DENKYUN_PALETTE = 0x75
SCOREBOARD_PALETTE_1 = 0x76
SCOREBOARD_PALETTE_2 = 0x77
SCOREBOARD_PALETTE_3 = 0x78
SCOREBOARD_ICONS_PALETTE = 0x79
DRAW_SPRITE_PALETTE = 0x7A
FIRST_UNUSED_B_PALETTE = 0x7B
FREE            = 0xFF

; The black and white palettes are always loaded at indexes 6 (value 0xC) and 7 (value 0x0E)
PALETTE_STATIC_BLACK = 0x0C
PALETTE_STATIC_WHITE = 0x0E

; Player powerup flags

remote_control_REMOTE_CONTROL = 0x01

POWERUPS_RED_BOMBS = 0x0001
POWERUPS_KICK      = 0x0100
POWERUPS_PUNCH     = 0x0200
POWERUPS_BOMB_PASS = 0x2000
POWERUPS_WALL_PASS = 0x4000
POWERUPS_HEART     = 0x8000

GAME_MODE_MENU = 1 ; Includes main menu, victory screen, password screen, map screen, game over screen
GAME_MODE_STORY = 2
GAME_MODE_BATTLE = 3 
GAME_MODE_BATTLE_MENU = 6 ; Includes the battle menu and scoreboard

; Poison state
POISON_TIMER_MASK = 0x3FF
POISON_TIMER_MAX = POISON_TIMER_MASK
POISON_FLASHING_VISIBLE = 0x400
POISON_INVISIBILITY = 0x800
POISON_MIN_SPEED = 0x1000
POISON_MAX_SPEED = 0x2000
POISON_AUTO_BOMB_DROP = 0x4000
POISON_NO_BOMBS = 0x8000
POISON_MIN_FIRE_SINGLE_BOMB = 0x10000

; Game flags

GAME_FLAGS_DEBUG_MENU = 0x1
GAME_FLAGS_LEVEL_END = 0x4
GAME_FLAGS_BATTLE_DELAY = 0x8
GAME_FLAGS_BATTLE_MENU = 0x10
GAME_FLAGS_UNKNOWN = 0x20
GAME_FLAGS_PAUSED = 0x40
GAME_FLAGS_SCREEN_TRANSITION = 0x80

; Sound constants

SOUND_MENU_SELECT = 0x00
SOUND_MENU_CONFIRM = 0x01
SOUND_BONUS = 0x02
SOUND_EXTRA_LIFE = 0x03
SOUND_BOMB_LAND = 0x04
SOUND_TIMER_WARNING = 0x05
SOUND_PUNCH = 0x07
SOUND_POISON = 0x0A
SOUND_STEP = 0x0C
SOUND_CROWD_CHEER = 0x0D
SOUND_PAUSE = 0x0E
SOUND_DEFUSE = 0x0F
SOUND_CROWD_WHISTLE = 0x11
SOUND_CROWD_CHEER_2 = 0x12
SOUND_CRANE = 0x17
SOUND_BUILDING_CRUMBLE = 0x1A
SOUND_BIG_EXPLOSION = 0x1B
SOUND_ERROR = 0x1D
SOUND_EXPLOSION = 0x21
SOUND_ENEMY_DEATH = 0x22
SOUND_STEP_ALT = 0x2E
SOUND_DEATH = 0x3F

; Buttons

BUTTON_R      = 0x0010
BUTTON_L      = 0x0020
BUTTON_X      = 0x0040
BUTTON_A      = 0x0080
BUTTON_RIGHT  = 0x0100
BUTTON_LEFT   = 0x0200
BUTTON_DOWN   = 0x0400
BUTTON_UP     = 0x0800
BUTTON_START  = 0x1000
BUTTON_SELECT = 0x2000
BUTTON_Y      = 0x4000
BUTTON_B      = 0x8000

; Directions

DIR_RIGHT = high(BUTTON_RIGHT)
DIR_LEFT  = high(BUTTON_LEFT)
DIR_DOWN  = high(BUTTON_DOWN)
DIR_UP    = high(BUTTON_UP)

; Level flags

; Story mode only spawn locations
LEVEL_FLAGS_SPAWN_DEFAULT        = 0x0001
LEVEL_FLAGS_SPAWN_BOSS           = 0x0002
LEVEL_FLAGS_SPAWN_BOSS_ALT       = 0x0003
LEVEL_FLAGS_SPAWN_WORLD_5        = 0x0005

LEVEL_FLAGS_DEMO                 = 0x0001
LEVEL_FLAGS_SOFTBLOCK_ANYWHERE   = 0x0004 ; Allow softblocks on every empty space
LEVEL_FLAGS_WESTERN              = 0x0008 ; Battle only
LEVEL_FLAGS_SPEED_MODE           = 0x0010 ; Battle only
LEVEL_FLAGS_WARP_ZONE            = 0x0020
LEVEL_FLAGS_JUMP_ZONE            = 0x0040
; 0x80 - unknown
LEVEL_FLAGS_POWER_ZONE           = 0x0100 ; Battle only
LEVEL_FLAGS_WESTERN_ALT          = 0x0200 ; Like Western, but allows softblocks anywhere
LEVEL_FLAGS_LIGHT_ZONE           = 0x0400 ; Used to fix the scoreboard graphics in Light Zone
LEVEL_FLAGS_TUNNEL_ZONE          = 0x0800 ; Blocks softblocks inside tunnels
LEVEL_FLAGS_BELT_ZONE            = 0x1000
; 0x2000 - unknown
LEVEL_FLAGS_FLOWER_ZONE          = 0x4000 ; Used in Flower Zone, NOT related to flower growth, tractors or clouds
LEVEL_FLAGS_HARDCODED_HARDBLOCKS = 0x8000 ; For cases where hardblocks can't be automatically inferred from the level structures, like 3_8. Hardcoded to values 0804 and 0808.

; Hidden Bonus Conditions

BONUS_COND_LIVES_DROP_TO_ZERO  = 0
BONUS_COND_DONT_MOVE           = 1
BONUS_COND_DONT_MOVE_ON_EXIT   = 2
BONUS_COND_PRESS_START         = 3
BONUS_COND_BOMBS_IN_CORNERS    = 4
BONUS_COND_UNCOVER_ALL_BONUSES = 5
BONUS_COND_COMBO_OF_3          = 6
BONUS_COND_SPAWN_ENEMY         = 7
BONUS_COND_5_PUNCHES           = 8
BONUS_COND_PUNCHED_BOMB_HIT    = 9
BONUS_COND_PLACE_6_BOMBS       = 10
BONUS_COND_SCORE_ENDS_WITH_20  = 11

; Battle menu settings

BATTLE_MENU_SETTING_PLAYER_1   = 0
BATTLE_MENU_SETTING_PLAYER_2   = 1
BATTLE_MENU_SETTING_PLAYER_3   = 2
BATTLE_MENU_SETTING_PLAYER_4   = 3
BATTLE_MENU_SETTING_COM_LEVEL  = 4
BATTLE_MENU_SETTING_GAME_COUNT = 5
BATTLE_MENU_SETTING_STAGE      = 6

; Player hit flags
HIT_FLAG_BLAST = 0x1
HIT_FLAG_PUNCHED_BOMB = 0x80

; Hardware definitions

; TM/TS

BG1_EN = 0x01
BG2_EN = 0x02
BG3_EN = 0x04
BG4_EN = 0x08
OBJ_EN = 0x10

; CGWSEL & CGADSUB

COLMAT_DIRECT        = 0x01
COLMAT_USE_SUBSCREEN = 0x02
COLMAT_BG1           = 0x0100
COLMAT_BG2           = 0x0200
COLMAT_BG3           = 0x0400
COLMAT_BG4           = 0x0800
COLMAT_OBJ           = 0x1000
COLMAT_BACKDROP      = 0x2000
COLMAT_HALF_MODE     = 0x4000
COLMAT_SUBSTRACT     = 0x8000

; Misc. constants
STORY_MODE_TIMER_TICKS = 15