nop()
track	(0x4)
inst	(0x4)
c6(0xa)
c6(0x7)
pan	(50)
volume	(90)
vol_range	(2)
play	('F#4', far=True)
play	('B-4')
play	('F-5')
pause	(3)
play	('F#5')
stop	('F-5')
stop	('F#5', pause=True)
vol_range	(3)
play	('G-5')
stop	('G-5', pause=6)
vol_range	(2)
play	('G-5')
stop	('F#4')
stop	('B-4')
pause	(12)
stop	('G-5')
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
stop	('G-5', pause=True)
stop	('F#4')
stop	('B-4')
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
stop	('B-4', pause=True)
stop	('F#4')
vol_range	(3)
play	('C-5')
vol_range	(2)
play	('F#4')
stop	('G-5', pause=True)
stop	('F#4')
stop	('C-5')
play	('F#5')
play	('C-5')
vol_range	(1)
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
pause	(11)
stop	('F#5')
pause	(1)
vol_range	(3)
play	('G-5')
play	('D-5')
play	('A-4')
pause	(12)
stop	('G-5')
stop	('A-4')
stop	('D-5')
vol_range	(2)
play	('E-5')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C-5')
vol_range	(1)
play	('G-4')
pause	(24)
stop	('E-5')
stop	('G-4')
stop	('C-5')
vol_range	(2)
play	('D-5')
vol_range	(1)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('F-5')
play	('B-4')
play	('F#4')
pause	(3)
stop	('F-5')
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('G-5')
pause	(6)
stop	('F#4')
stop	('G-5')
stop	('B-4')
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
pause	(12)
stop	('G-5')
stop	('F#4')
stop	('B-4')
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
stop	('B-4', pause=True)
stop	('F#4')
vol_range	(3)
play	('C-5')
vol_range	(2)
play	('F#4')
stop	('G-5', pause=True)
stop	('F#4')
stop	('C-5')
vol_range	(3)
play	('F#5')
vol_range	(2)
play	('C-5')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
stop	('F#5', pause=True)
play	('G-5')
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('G-5', pause=True)
stop	('A-4')
stop	('D-5')
play	('A-5')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
stop	('A-5', pause=True)
play	('B-5')
play	('D-5')
play	('A-4')
pause	(24)
stop	('D-5')
stop	('A-4')
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
pause	(12)
stop	('D-5')
stop	('A-4')
play	('C-5')
play	('G-4')
stop	('C-5', pause=True)
stop	('G-4')
play	('D-5')
play	('A-4')
stop	('B-5', pause=True)
stop	('A-4')
stop	('D-5')
play	('F-5')
vol_range	(3)
play	('B-4')
vol_range	(2)
play	('F#4')
pause	(3)
stop	('F-5')
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('G-5')
pause	(6)
stop	('F#4')
stop	('G-5')
stop	('B-4')
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
pause	(12)
stop	('G-5')
stop	('F#4')
stop	('B-4')
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
stop	('B-4', pause=True)
stop	('F#4')
play	('C-5')
play	('F#4')
stop	('G-5', pause=True)
stop	('F#4')
stop	('C-5')
play	('F#5')
play	('C-5')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
stop	('F#5', pause=True)
play	('G-5')
play	('D-5')
play	('A-4')
stop	('G-5', pause=True)
stop	('A-4')
stop	('D-5')
play	('E-5')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C-5')
play	('A-4')
pause	(24)
stop	('E-5')
play	('E-5')
stop	('E-5', pause=8)
vol_range	(3)
play	('F#5')
stop	('F#5', pause=8)
play	('G-5')
pause	(8)
stop	('A-4')
stop	('G-5')
stop	('C-5')
vol_range	(2)
play	('A-5')
play	('F#5')
play	('D-5')
pause	(3)
stop	('A-5')
play	('A#5')
stop	('A#5', pause=True)
play	('B-5')
pause	(18)
stop	('D-5')
stop	('F#5')
play	('D-5')
play	('A-4')
pause	(12)
stop	('D-5')
stop	('A-4')
play	('F#5')
play	('D-5')
pause	(24)
stop	('F#5')
stop	('D-5')
play	('F#5')
play	('D-5')
pause	(12)
stop	('B-5')
play	('B-5')
stop	('D-5', pause=True)
stop	('F#5')
play	('F#5')
play	('D-5')
stop	('B-5', pause=True)
stop	('D-5')
stop	('F#5')
play	('A#5')
play	('C#5')
play	('G#4')
stop	('C#5', pause=True)
stop	('G#4')
play	('C#5')
play	('G#4')
stop	('C#5', pause=True)
stop	('G#4')
pause	(12)
play	('F-5')
play	('C#5')
pause	(24)
stop	('F-5')
stop	('C#5')
play	('G#4')
play	('F-4')
pause	(12)
stop	('G#4')
stop	('F-4')
play	('C#5')
play	('G#4')
stop	('C#5', pause=True)
stop	('G#4')
play	('F-5')
play	('A#4')
stop	('A#5', pause=True)
stop	('A#4')
stop	('F-5')
vol_range	(3)
play	('D-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-4', pause=True)
stop	('A-4', pause=True)
stop	('D-5')
play	('C-5')
play	('A-4')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
stop	('A-4')
play	('F#5')
play	('D-5')
play	('A-4')
pause	(24)
stop	('F#5')
stop	('A-4')
stop	('D-5')
play	('C-5')
play	('D-5')
play	('A-4')
pause	(12)
stop	('C-5')
stop	('A-4', pause=True)
stop	('D-5')
play	('C-5')
play	('D-5')
play	('A-4')
stop	('C-5', pause=True)
stop	('A-4')
stop	('D-5')
vol_range	(3)
play	('D-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-4', pause=True)
stop	('A-4')
stop	('D-5')
play	('A-4')
play	('D-5')
stop	('A-4', pause=True)
stop	('D-5')
play	('C-5')
stop	('C-5', pause=True)
play	('F#5')
play	('D-5')
play	('A-4')
pause	(32)
pause	(28)
stop	('F#5')
stop	('A-4')
stop	('D-5')
play	('F-5')
play	('B-4')
play	('F#4')
pause	(3)
stop	('F-5')
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('G-5')
pause	(6)
stop	('F#4')
stop	('G-5')
stop	('B-4')
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
pause	(12)
stop	('G-5')
stop	('F#4')
stop	('B-4')
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
stop	('B-4', pause=True)
stop	('F#4')
vol_range	(3)
play	('C-5')
vol_range	(2)
play	('F#4')
stop	('G-5', pause=True)
stop	('F#4')
stop	('C-5')
play	('F#5')
play	('C-5')
vol_range	(1)
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
pause	(11)
stop	('F#5')
pause	(1)
vol_range	(3)
play	('G-5')
play	('D-5')
play	('A-4')
pause	(12)
stop	('G-5')
stop	('A-4')
stop	('D-5')
vol_range	(2)
play	('E-5')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C-5')
vol_range	(1)
play	('G-4')
pause	(24)
stop	('E-5')
stop	('G-4')
stop	('C-5')
vol_range	(2)
play	('D-5')
vol_range	(1)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('F-5')
play	('B-4')
play	('F#4')
pause	(3)
stop	('F-5')
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('G-5')
pause	(6)
stop	('F#4')
stop	('G-5')
stop	('B-4')
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
pause	(12)
stop	('G-5')
stop	('F#4')
stop	('B-4')
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
stop	('B-4', pause=True)
stop	('F#4')
vol_range	(3)
play	('C-5')
vol_range	(2)
play	('F#4')
stop	('G-5', pause=True)
stop	('F#4')
stop	('C-5')
vol_range	(3)
play	('F#5')
vol_range	(2)
play	('C-5')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
stop	('F#5', pause=True)
play	('G-5')
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('G-5', pause=True)
stop	('A-4')
stop	('D-5')
play	('A-5')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
stop	('A-5', pause=True)
play	('B-5')
play	('D-5')
play	('A-4')
pause	(24)
stop	('D-5')
stop	('A-4')
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
pause	(12)
stop	('D-5')
stop	('A-4')
play	('C-5')
play	('G-4')
stop	('C-5', pause=True)
stop	('G-4')
play	('D-5')
play	('A-4')
stop	('B-5', pause=True)
stop	('A-4')
stop	('D-5')
play	('F-5')
vol_range	(3)
play	('B-4')
vol_range	(2)
play	('F#4')
pause	(3)
stop	('F-5')
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('G-5')
pause	(6)
stop	('F#4')
stop	('G-5')
stop	('B-4')
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
pause	(12)
stop	('G-5')
stop	('F#4')
stop	('B-4')
vol_range	(3)
play	('G-5')
vol_range	(2)
play	('B-4')
play	('F#4')
stop	('B-4', pause=True)
stop	('F#4')
play	('C-5')
play	('F#4')
stop	('G-5', pause=True)
stop	('F#4')
stop	('C-5')
play	('F#5')
play	('C-5')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
stop	('F#5', pause=True)
play	('G-5')
play	('D-5')
play	('A-4')
stop	('G-5', pause=True)
stop	('A-4')
stop	('D-5')
play	('E-5')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C-5')
play	('A-4')
pause	(24)
stop	('E-5')
play	('E-5')
stop	('E-5', pause=8)
vol_range	(3)
play	('F#5')
stop	('F#5', pause=8)
play	('G-5')
pause	(8)
stop	('A-4')
stop	('G-5')
stop	('C-5')
vol_range	(2)
play	('A-5')
play	('F#5')
play	('D-5')
pause	(3)
stop	('A-5')
play	('A#5')
stop	('A#5', pause=True)
play	('B-5')
pause	(18)
stop	('D-5')
stop	('F#5')
play	('D-5')
play	('A-4')
pause	(12)
stop	('D-5')
stop	('A-4')
play	('F#5')
play	('D-5')
pause	(24)
stop	('F#5')
stop	('D-5')
play	('F#5')
play	('D-5')
pause	(12)
stop	('B-5')
play	('B-5')
stop	('D-5', pause=True)
stop	('F#5')
play	('F#5')
play	('D-5')
stop	('B-5', pause=True)
stop	('D-5')
stop	('F#5')
play	('A#5')
play	('C#5')
play	('G#4')
stop	('C#5', pause=True)
stop	('G#4')
play	('C#5')
play	('G#4')
stop	('C#5', pause=True)
stop	('G#4')
pause	(12)
play	('F-5')
play	('C#5')
pause	(24)
stop	('F-5')
stop	('C#5')
play	('G#4')
play	('F-4')
pause	(12)
stop	('G#4')
stop	('F-4')
play	('C#5')
play	('G#4')
stop	('C#5', pause=True)
stop	('G#4')
play	('F-5')
play	('A#4')
stop	('A#5', pause=True)
stop	('A#4')
stop	('F-5')
vol_range	(3)
play	('D-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-4', pause=True)
stop	('A-4', pause=True)
stop	('D-5')
play	('C-5')
play	('A-4')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
stop	('A-4')
play	('F#5')
play	('D-5')
play	('A-4')
pause	(24)
stop	('F#5')
stop	('A-4')
stop	('D-5')
play	('C-5')
play	('D-5')
play	('A-4')
pause	(12)
stop	('C-5')
stop	('A-4', pause=True)
stop	('D-5')
play	('C-5')
play	('D-5')
play	('A-4')
stop	('C-5', pause=True)
stop	('A-4')
stop	('D-5')
vol_range	(3)
play	('D-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-4', pause=True)
stop	('A-4')
stop	('D-5')
play	('A-4')
play	('D-5')
stop	('A-4', pause=True)
stop	('D-5')
play	('C-5')
stop	('C-5', pause=True)
play	('F#5')
play	('D-5')
play	('A-4')
pause	(32)
pause	(28)
stop	('F#5')
stop	('A-4')
stop	('D-5')
c6(0x6)
song	(12)
halt	()
halt	()
