nop()
track	(0x4)
inst	(0x0)
c6(0x7)
volume	(120)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
vol_range	(3)
play	('B-5', far=True)
stop	('B-5', pause=12)
pause	(12)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('G-5')
stop	('G-5', pause=24)
pause	(30)
play	('F-5')
stop	('F-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('F-5')
stop	('F-5', pause=6)
play	('A-5')
stop	('A-5', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=12)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(26)
play	('B-5')
stop	('B-5', pause=12)
pause	(12)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('G-5')
stop	('G-5', pause=24)
play	('D-6')
stop	('D-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
pause	(6)
play	('F-5')
stop	('F-5', pause=18)
pause	(6)
play	('E-5')
stop	('E-5', pause=18)
pause	(6)
play	('D-5')
stop	('D-5', pause=18)
pause	(12)
play	('D-6')
stop	('D-6', pause=6)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('B-5')
stop	('B-5', pause=18)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(2)
play	('B-5')
stop	('B-5', pause=12)
pause	(12)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('G-5')
stop	('G-5', pause=24)
pause	(30)
play	('F-5')
stop	('F-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('F-5')
stop	('F-5', pause=6)
play	('A-5')
stop	('A-5', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=12)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(26)
play	('B-5')
stop	('B-5', pause=12)
pause	(12)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('G-5')
stop	('G-5', pause=24)
play	('D-6')
stop	('D-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
pause	(6)
play	('F-5')
stop	('F-5', pause=18)
pause	(6)
play	('E-5')
stop	('E-5', pause=18)
pause	(6)
play	('D-5')
stop	('D-5', pause=18)
pause	(12)
play	('D-6')
stop	('D-6', pause=6)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('B-5')
stop	('B-5', pause=18)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(2)
inst	(0x5)
play	('C-6')
stop	('C-6', pause=24)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=24)
play	('D-6')
stop	('D-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('B-5')
stop	('B-5', pause=True)
play	('C#6')
stop	('C#6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
pause	(6)
play	('G-6')
stop	('G-6', pause=True)
pause	(6)
play	('F#6')
stop	('F#6', pause=18)
pause	(6)
play	('C-6')
stop	('C-6', pause=24)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=24)
play	('D-6')
stop	('D-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('G-5')
stop	('G-5', pause=True)
play	('F#5')
stop	('F#5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=18)
pause	(6)
play	('C-6')
stop	('C-6', pause=24)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=24)
play	('D-6')
stop	('D-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('B-5')
stop	('B-5', pause=True)
play	('C#6')
stop	('C#6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
pause	(6)
play	('G-6')
stop	('G-6', pause=True)
pause	(6)
play	('F#6')
stop	('F#6', pause=18)
pause	(6)
play	('C-6')
stop	('C-6', pause=24)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=24)
play	('D-6')
stop	('D-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-5')
stop	('B-5', pause=True)
play	('D-6')
stop	('D-6', pause=6)
play	('D#6')
stop	('D#6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
halt	()
halt	()
compress()
