nop()
inst	(0x2)
c6(0x7)
volume	(100)
vol_range	(3)
play	('G-4', far=True)
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('F-4', far=True)
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=12)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('F-4', far=True)
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=12)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('C-6')
stop	('C-6', pause=True)
play	('F-6')
stop	('F-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('F-4', far=True)
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=12)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('F-4', far=True)
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=12)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('C-6')
stop	('C-6', pause=True)
play	('F-6')
stop	('F-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=24)
play	('F-4', far=True)
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=12)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
play	('C-5')
stop	('C-5', pause=18)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=18)
play	('D-5')
stop	('D-5', pause=18)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=18)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=12)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=18)
pause	(6)
play	('C-5')
stop	('C-5', pause=18)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=18)
play	('D-5')
stop	('D-5', pause=18)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=18)
play	('E-5')
stop	('E-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-5')
stop	('G-5', pause=12)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=18)
pause	(6)
play	('C-5')
stop	('C-5', pause=18)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=18)
play	('D-5')
stop	('D-5', pause=18)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=18)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=12)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=18)
pause	(6)
play	('C-5')
stop	('C-5', pause=18)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=18)
play	('D-5')
stop	('D-5', pause=18)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=18)
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
pause	(32)
pause	(10)
c6(0x6)
song	(11)
halt	()
halt	()
compress()
