nop()
track	(0x1)
inst	(0x5)
c6(0xa)
c6(0x7)
pan	(80)
volume	(110)
pause	(255, set=False)
pause	(255, set=False)
pause	(24)
vol_range	(3)
play	('F-6', far=True)
stop	('F-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('F-6')
stop	('F-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(28)
play	('D-6')
stop	('D-6', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
pause	(6)
play	('F-6')
stop	('F-6', pause=18)
play	('F-6')
stop	('F-6', pause=True)
pause	(6)
play	('E-6')
stop	('E-6', pause=12)
pause	(12)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('D-6')
stop	('D-6', pause=6)
play	('C-6')
stop	('C-6', pause=18)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('D-6')
stop	('D-6', pause=12)
play	('C#6')
stop	('C#6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('F-6')
stop	('F-6', pause=True)
pause	(6)
play	('F-6')
stop	('F-6', pause=True)
pause	(6)
play	('E-6')
stop	('E-6', pause=18)
pause	(6)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('C-6')
stop	('C-6', pause=12)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('F-6')
stop	('F-6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('F-6')
stop	('F-6', pause=True)
play	('G-6')
stop	('G-6', pause=True)
play	('A-6')
stop	('A-6', pause=True)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(28)
play	('D-6')
stop	('D-6', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
pause	(6)
play	('F-6')
stop	('F-6', pause=18)
play	('F-6')
stop	('F-6', pause=True)
pause	(6)
play	('E-6')
stop	('E-6', pause=12)
pause	(12)
play	('D-6')
stop	('D-6', pause=True)
pause	(12)
play	('D-6')
stop	('D-6', pause=6)
play	('C-6')
stop	('C-6', pause=18)
halt	()
halt	()
compress()

data += "\x00" # No clue why it's there. Plays fine without it.