nop()
track	(0x5)
inst	(0x4)
c6(0xa)
c6(0x7)
pan	(40)
volume	(90)
pause	(24)
vol_range	(3)
play	('D-5', far=True)
play	('G-5')
pause	(12)
stop	('D-5')
stop	('G-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(12)
stop	('C-5')
stop	('F-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
pause	(18)
stop	('C-5')
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('C-5')
play	('D-5')
stop	('C-5', pause=True)
stop	('D-5')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(24)
play	('D-5')
play	('G-5')
pause	(12)
stop	('D-5')
stop	('G-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(18)
stop	('C-5')
stop	('F-5')
play	('C-5')
play	('E-5')
pause	(6)
stop	('C-5')
stop	('E-5')
pause	(6)
play	('C-5')
play	('F-5')
pause	(18)
stop	('C-5')
stop	('F-5')
play	('E-5')
play	('C-5')
pause	(6)
stop	('E-5')
stop	('C-5')
pause	(6)
play	('C-5')
play	('F-5')
stop	('C-5', pause=True)
stop	('F-5')
pause	(30)
play	('D-5')
play	('G-5')
pause	(12)
stop	('D-5')
stop	('G-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(12)
stop	('C-5')
stop	('F-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
pause	(18)
stop	('C-5')
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('C-5')
play	('D-5')
stop	('C-5', pause=True)
stop	('D-5')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(24)
play	('D-5')
play	('G-5')
pause	(12)
stop	('D-5')
stop	('G-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(6)
stop	('C-5')
stop	('F-5')
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F-5')
play	('A-5')
stop	('F-5', pause=True)
stop	('A-5')
pause	(6)
play	('F-5')
play	('A-5')
pause	(12)
stop	('F-5')
stop	('A-5')
pause	(6)
play	('G-5')
play	('E-5')
stop	('G-5', pause=True)
stop	('E-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(30)
play	('D-5')
play	('G-5')
stop	('G-5', pause=14)
stop	('D-5')
pause	(4)
play	('D-5')
play	('F-5')
pause	(5)
stop	('D-5')
pause	(1)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(12)
stop	('C-5')
stop	('F-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
pause	(18)
stop	('C-5')
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('C-5')
play	('D-5')
stop	('C-5', pause=True)
stop	('D-5')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(24)
play	('D-5')
play	('G-5')
pause	(12)
stop	('D-5')
stop	('G-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(18)
stop	('C-5')
stop	('F-5')
play	('C-5')
play	('E-5')
pause	(6)
stop	('C-5')
stop	('E-5')
pause	(6)
play	('C-5')
play	('F-5')
pause	(18)
stop	('C-5')
stop	('F-5')
play	('E-5')
play	('C-5')
pause	(6)
stop	('E-5')
stop	('C-5')
pause	(6)
play	('C-5')
play	('F-5')
stop	('C-5', pause=True)
stop	('F-5')
pause	(30)
play	('D-5')
play	('G-5')
pause	(12)
stop	('D-5')
stop	('G-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(12)
stop	('C-5')
stop	('F-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
pause	(18)
stop	('C-5')
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('C-5')
play	('D-5')
stop	('C-5', pause=True)
stop	('D-5')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(24)
play	('D-5')
play	('G-5')
pause	(12)
stop	('D-5')
stop	('G-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(6)
stop	('C-5')
stop	('F-5')
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F-5')
play	('A-5')
stop	('F-5', pause=True)
stop	('A-5')
pause	(6)
play	('F-5')
play	('A-5')
pause	(12)
stop	('F-5')
stop	('A-5')
pause	(6)
play	('G-5')
play	('E-5')
stop	('G-5', pause=True)
stop	('E-5')
pause	(6)
play	('D-5')
play	('F-5')
stop	('D-5', pause=True)
stop	('F-5')
pause	(30)
play	('D-5')
play	('G-5')
stop	('G-5', pause=14)
stop	('D-5')
pause	(4)
play	('D-5')
play	('F-5')
pause	(5)
stop	('D-5')
pause	(1)
stop	('F-5')
pause	(32)
pause	(32)
pause	(8)
play	('C-5')
play	('F-5')
pause	(12)
stop	('C-5')
stop	('F-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
pause	(18)
stop	('C-5')
stop	('E-5')
pause	(6)
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('C-5')
play	('D-5')
stop	('C-5', pause=True)
stop	('D-5')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('G-4')
stop	('G-4', pause=18)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=12)
play	('A-4')
stop	('A-4', pause=18)
play	('A-4')
stop	('A-4', pause=12)
pause	(6)
play	('A-4')
stop	('A-4', pause=12)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=18)
pause	(6)
play	('G-4')
stop	('G-4', pause=18)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=12)
play	('A-4')
stop	('A-4', pause=18)
play	('A-4')
stop	('A-4', pause=12)
pause	(6)
play	('A-4')
stop	('A-4', pause=12)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=12)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=18)
pause	(6)
play	('G-4')
stop	('G-4', pause=18)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=12)
play	('A-4')
stop	('A-4', pause=18)
play	('A-4')
stop	('A-4', pause=12)
pause	(6)
play	('A-4')
stop	('A-4', pause=12)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=18)
pause	(6)
play	('G-4')
stop	('G-4', pause=18)
play	('G-4')
stop	('G-4', pause=12)
pause	(6)
play	('G-4')
stop	('G-4', pause=12)
play	('A-4')
stop	('A-4', pause=18)
play	('A-4')
stop	('A-4', pause=12)
pause	(6)
play	('A-4')
stop	('A-4', pause=12)
play	('E-4')
play	('E-5')
stop	('E-4', pause=True)
stop	('E-5')
play	('E-4')
play	('E-5')
stop	('E-4', pause=True)
stop	('E-5')
play	('G-5')
play	('G-4')
stop	('G-5', pause=True)
stop	('G-4')
play	('E-4')
play	('E-5')
stop	('E-4', pause=True)
stop	('E-5')
play	('B-5')
play	('B-4')
pause	(12)
stop	('B-5')
stop	('B-4')
play	('D-5')
vol_range	(2)
play	('D-6')
pause	(6)
stop	('D-5')
stop	('D-6')
vol_range	(3)
play	('D#5')
play	('D#6')
stop	('D#5', pause=True)
stop	('D#6')
play	('E-6')
play	('E-5')
stop	('E-6', pause=True)
stop	('E-5')
pause	(18)
play	('E-7', far=True)
stop	('E-7', pause=2)
play	('D-7')
stop	('D-7', pause=1)
play	('C-7')
stop	('C-7', pause=2)
play	('B-6')
stop	('B-6', pause=1)
play	('A-6')
stop	('A-6', pause=2)
play	('G-6')
stop	('G-6', pause=1)
play	('F-6')
stop	('F-6', pause=2)
play	('E-6')
stop	('E-6', pause=1)
play	('D-6')
stop	('D-6', pause=2)
play	('C-6')
stop	('C-6', pause=1)
play	('B-5')
stop	('B-5', pause=2)
play	('A-5')
stop	('A-5', pause=1)
play	('G-5')
stop	('G-5', pause=2)
play	('F-5')
stop	('F-5', pause=1)
play	('E-5')
stop	('E-5', pause=2)
play	('D-5')
stop	('D-5', pause=1)
halt	()
halt	()
compress()
