nop()
track	(0x9)
inst	(0x3)
c6(0x7)
volume	(110)
vol_range	(3)
play	('B-2', far=True)
pause	(18)
play	('B-2')
stop	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=6)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=6)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=6)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=6)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=6)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=12)
play	('B-2', far=True)
stop	('B-2', pause=12)
play	('B-2')
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=6)
play	('G#4', far=True)
stop	('G#4', pause=True)
play	('B-2', far=True)
stop	('B-2', pause=True)
play	('B-2')
stop	('B-2', pause=12)
play	('G#4', far=True)
stop	('G#4', pause=24)
halt	()
halt	()
compress()
