nop()
track	(0x4)
pause	(255, set=False)
pause	(255, set=False)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
bend	(4, far=True)
bend	(14)
pause	(1)
bend	(22)
bend	(26, pause=True)
bend	(33, pause=True)
bend	(41)
bend	(51, pause=True)
bend	(59, pause=True)
bend	(63, pause=True)
pause	(15)
bend	(0, far=True, pause = True)
pause	(4)
bend	(6)
pause	(1)
bend	(28, far=True, pause = True)
bend	(49, far=True, pause = True)
bend	(61, pause=True)
bend	(63, pause=True)
pause	(16)
bend	(0, far=True, pause = True)
pause	(5)
bend	(16, far=True, pause = True)
bend	(37, far=True, pause = True)
pause	(1)
bend	(55, far=True, pause = True)
bend	(63, pause=True)
pause	(21)
bend	(0, far=True, pause = True)
pause	(255, set=False)
pause	(255, set=False)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(26)
bend	(4)
bend	(14)
pause	(1)
bend	(22)
bend	(26, pause=True)
bend	(33, pause=True)
bend	(41)
bend	(51, pause=True)
bend	(59, pause=True)
bend	(63, pause=True)
pause	(15)
bend	(0, far=True, pause = True)
pause	(4)
bend	(6)
pause	(1)
bend	(28, far=True, pause = True)
bend	(49, far=True, pause = True)
bend	(61, pause=True)
bend	(63, pause=True)
pause	(16)
bend	(0, far=True, pause = True)
pause	(5)
bend	(16, far=True, pause = True)
bend	(37, far=True, pause = True)
pause	(1)
bend	(55, far=True, pause = True)
bend	(63, pause=True)
pause	(21)
bend	(0, far=True, pause = True)
halt	()
halt	()
