nop()
inst	(0x0)
c6(0x7)
volume	(100)
pause	(12)
vol_range	(2)
play	('F-4', far=True)
stop	('F-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('C-5')
stop	('C-5', pause=6)
pause	(18)
play	('A-4')
pause	(32)
stop	('A-4', pause=4)
pause	(12)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=6)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('F-4')
stop	('F-4', pause=12)
play	('F-4')
stop	('F-4', pause=12)
play	('D-4')
play	('F-4')
stop	('F-4', pause=True)
stop	('D-4', pause=True)
pause	(24)
volume	(127)
play	('E-4')
pause	(8)
volume	(124)
pause	(2)
volume	(123)
pause	(15)
volume	(121)
pause	(4)
volume	(118)
pause	(3)
volume	(117)
pause	(4)
volume	(113)
pause	(3)
volume	(112)
pause	(3)
volume	(110)
pause	(3)
volume	(107)
pause	(3)
volume	(106)
pause	(3)
volume	(104)
pause	(3)
volume	(101)
pause	(3)
volume	(100)
pause	(12)
volume	(97)
pause	(5)
volume	(96)
pause	(4)
volume	(94)
pause	(5)
volume	(93)
pause	(3)
volume	(91)
pause	(3)
volume	(90)
pause	(3)
volume	(88)
pause	(3)
volume	(87)
pause	(3)
volume	(85)
pause	(3)
volume	(84)
pause	(3)
volume	(82)
pause	(4)
volume	(81)
pause	(3)
volume	(79)
pause	(3)
volume	(78)
pause	(3)
volume	(76)
pause	(2)
volume	(75)
pause	(2)
volume	(73)
pause	(2)
volume	(72)
pause	(2)
volume	(70)
pause	(3)
volume	(69)
pause	(2)
volume	(67)
pause	(2)
volume	(65)
stop	('E-4')
volume	(127)
pause	(24)
volume	(127)
play	('D-4')
stop	('D-4', pause=12)
play	('F-4')
stop	('F-4', pause=12)
play	('A-4')
stop	('A-4', pause=12)
play	('C-5')
stop	('C-5', pause=6)
pause	(18)
play	('A-4')
pause	(32)
stop	('A-4', pause=4)
pause	(12)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=6)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('F-4')
stop	('F-4', pause=12)
play	('F-4')
stop	('F-4', pause=12)
play	('F-4')
stop	('F-4', pause=True)
pause	(30)
volume	(127)
play	('E-4')
pause	(8)
volume	(124)
pause	(2)
volume	(123)
pause	(15)
volume	(121)
pause	(4)
volume	(118)
pause	(3)
volume	(117)
pause	(4)
volume	(113)
pause	(3)
volume	(112)
pause	(3)
volume	(110)
pause	(3)
volume	(107)
pause	(3)
volume	(106)
pause	(3)
volume	(104)
pause	(3)
volume	(101)
pause	(3)
volume	(100)
pause	(12)
volume	(97)
pause	(5)
volume	(96)
pause	(4)
volume	(94)
pause	(5)
volume	(93)
pause	(3)
volume	(91)
pause	(3)
volume	(90)
pause	(3)
volume	(88)
pause	(3)
volume	(87)
pause	(3)
volume	(85)
pause	(3)
volume	(84)
pause	(3)
volume	(82)
pause	(4)
volume	(81)
pause	(3)
volume	(79)
pause	(3)
volume	(78)
pause	(3)
volume	(76)
pause	(2)
volume	(75)
pause	(2)
volume	(73)
pause	(2)
volume	(72)
pause	(2)
volume	(70)
pause	(3)
volume	(69)
pause	(2)
volume	(67)
pause	(2)
volume	(65)
stop	('E-4')
volume	(127)
pause	(24)
volume	(80)
inst	(0x1)
vol_range	(3)
play	('A-5', far=True)
stop	('A-5', pause=6)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=12)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('D#5')
stop	('D#5', pause=3)
pause	(9)
vol_range	(3)
play	('A-5')
pause	(32)
stop	('A-5', pause=28)
play	('A-5')
stop	('A-5', pause=6)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=12)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('C#5')
stop	('C#5', pause=3)
pause	(9)
play	('A-5')
stop	('A-5', pause=24)
vol_range	(3)
play	('B-5')
stop	('B-5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=4)
vol_range	(2)
play	('B-5')
stop	('B-5', pause=4)
play	('A-5')
stop	('A-5', pause=4)
vol_range	(3)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=12)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('D#5')
stop	('D#5', pause=3)
pause	(9)
vol_range	(3)
play	('A-5')
pause	(32)
stop	('A-5', pause=28)
play	('A-5')
stop	('A-5', pause=6)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(18)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=12)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('G#5')
stop	('G#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A#4')
stop	('A#4', pause=True)
pause	(18)
inst	(0x0)
pause	(12)
vol_range	(3)
play	('C-5')
c6(0x7)
volume	(100)
stop	('C-5', pause=6)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(30)
play	('A#4')
stop	('A#4', pause=6)
pause	(18)
play	('A#4')
stop	('A#4', pause=6)
pause	(18)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
vol_range	(3)
play	('C-4')
stop	('C-4', pause=6)
vol_range	(2)
play	('B-3')
stop	('B-3', pause=6)
vol_range	(3)
play	('C-4')
stop	('C-4', pause=6)
pause	(18)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=6)
pause	(18)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=6)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
pause	(6)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
volume	(115)
pause	(12)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=6)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
pause	(30)
vol_range	(2)
play	('D-4')
stop	('D-4', pause=6)
play	('D-4')
stop	('D-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=6)
play	('F-4')
stop	('F-4', pause=6)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(18)
play	('C-4')
stop	('C-4', pause=6)
play	('C-4')
stop	('C-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-4')
stop	('C-4', pause=6)
play	('D#4')
stop	('D#4', pause=6)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('C-4')
stop	('C-4', pause=True)
play	('B-3')
stop	('B-3', pause=True)
play	('C-4')
stop	('C-4', pause=True)
pause	(6)
play	('A-3')
stop	('A-3', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('G-4')
stop	('G-4', pause=True)
pause	(6)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-3')
stop	('A-3', pause=True)
pause	(18)
play	('A-3')
stop	('A-3', pause=6)
play	('A-3')
stop	('A-3', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-3')
stop	('A-3', pause=6)
play	('G-4')
stop	('G-4', pause=6)
pause	(6)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-3')
stop	('A-3', pause=24)
c6(0x6)
song	(5)
halt	()
halt	()
compress()
