nop()
track	(0x2)
c6(0xa)
c6(0x7)
inst	(0x4)
volume	(50)
pan	(80)
pause	(12)
vol_range	(3)
play	('A-4', far=True)
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('B-3')
stop	('B-3', pause=6)
play	('B-3')
stop	('B-3', pause=6)
pause	(12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('C#5')
stop	('C#5', pause=6)
play	('C#5')
stop	('C#5', pause=6)
inst	(0x4)
pause	(12)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('B-3')
stop	('B-3', pause=6)
play	('B-3')
stop	('B-3', pause=6)
pause	(12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('C#5')
stop	('C#5', pause=6)
play	('C#5')
stop	('C#5', pause=6)
volume	(78)
c6(0x7)
play	('F#4')
pause	(6)
play	('F-4')
stop	('F#4')
stop	('F-4', pause=True)
vol_range	(2)
play	('F#4')
stop	('F#4', pause=True)
vol_range	(3)
play	('D-4')
stop	('D-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('F#4')
stop	('F#4', pause=True)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C#6')
stop	('C#6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C#6')
stop	('C#6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C#6')
stop	('C#6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
vol_range	(2)
play	('F#4')
stop	('F#4', pause=True)
vol_range	(3)
play	('D-4')
stop	('D-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('F#4')
stop	('F#4', pause=True)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C#6')
stop	('C#6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C#6')
stop	('C#6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C#6')
stop	('C#6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
halt	()
halt	()
compress()
