nop()
track	(0x1)
inst	(0x4)
c6(0xa)
c6(0x7)
volume	(65)
pan	(40)
pause	(12)
vol_range	(3)
play	('A-5', far=True)
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('G#6')
stop	('G#6', pause=6)
play	('G#6')
stop	('G#6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('C#7')
stop	('C#7', pause=6)
play	('C#7')
stop	('C#7', pause=6)
play	('B-6')
stop	('B-6', pause=6)
play	('B-6')
stop	('B-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
inst	(0x4)
pause	(12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('G#6')
stop	('G#6', pause=6)
play	('G#6')
stop	('G#6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('G#5')
stop	('G#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('D-7')
stop	('D-7', pause=6)
play	('C#7')
stop	('C#7', pause=6)
play	('C#7')
stop	('C#7', pause=6)
play	('B-6')
stop	('B-6', pause=6)
play	('B-6')
stop	('B-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('A-6')
stop	('A-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('F#6')
stop	('F#6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
play	('C#6')
stop	('C#6', pause=6)
volume	(115)
inst	(0x0)
play	('D-4', far=True)
pause	(6)
play	('E-4')
stop	('D-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
pause	(18)
play	('D-4')
stop	('D-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
play	('E-4')
stop	('E-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(18)
play	('E-4')
stop	('E-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(18)
play	('G-4')
stop	('G-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('G-4')
stop	('G-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('A-4')
stop	('A-4', pause=24)
play	('A-4')
stop	('A-4', pause=24)
play	('A-4')
stop	('A-4', pause=24)
play	('A-4')
stop	('A-4', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('D-4')
stop	('D-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
play	('D-4')
stop	('D-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
play	('E-4')
stop	('E-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(18)
play	('E-4')
stop	('E-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('G#4')
stop	('G#4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(18)
play	('G-4')
stop	('G-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('G-4')
stop	('G-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('A-4')
stop	('A-4', pause=24)
play	('A-4')
stop	('A-4', pause=24)
play	('A-4')
stop	('A-4', pause=24)
play	('A-4')
stop	('A-4', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
halt	()
halt	()
compress()
