nop()
track	(0x6)
inst	(0x3)
c6(0xa)
c6(0x7)
vol_range	(3)
play	('C-9', far=True)
volume	(90)
pan	(70)
stop	('C-9', pause=6)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
pause	(6)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
play	('C-9')
stop	('C-9', pause=True)
halt	()
halt	()
compress()
