nop()
inst	(0x2)
c6(0x7)
vol_range	(3)
play	('D-4', far=True)
volume	(95)
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
inst	(0x2)
play	('D-4', far=True)
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
inst	(0x2)
play	('D-4', far=True)
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
inst	(0x2)
play	('D-4', far=True)
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=12)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=12)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-4')
stop	('G-4', pause=12)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
c6(0x6)
song	(22)
halt	()
halt	()
compress()
