nop()
track	(0x1)
inst	(0x4)
c6(0xa)
c6(0x7)
pan	(40)
volume	(95)
vol_range	(2)
play	('E-5', far=True)
pause	(6)
play	('G-5')
stop	('E-5')
stop	('G-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-5', far=True)
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-5', far=True)
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-5', far=True)
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('B-5', far=True)
stop	('B-5', pause=True)
play	('E-4', far=True)
stop	('E-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('F-4')
stop	('F-4', pause=True)
vol_range	(2)
play	('F-4')
stop	('F-4', pause=True)
vol_range	(3)
play	('F-5')
stop	('F-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
pause	(32)
pause	(10)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#4')
stop	('F#4', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
inst	(0x1)
c6(0x7)
volume	(110)
play	('E-6')
pause	(32)
pause	(28)
play	('D-6')
stop	('E-6')
pause	(12)
stop	('D-6')
play	('E-6')
stop	('E-6', pause=True)
play	('F#6')
stop	('F#6', pause=True)
play	('F#6')
pause	(32)
stop	('F#6', pause=28)
play	('F#6')
stop	('F#6', pause=12)
play	('G-6')
stop	('G-6', pause=12)
play	('A-6')
pause	(32)
stop	('A-6', pause=4)
play	('G-6')
stop	('G-6', pause=24)
play	('F#6')
stop	('F#6', pause=24)
play	('E-6')
stop	('E-6', pause=23)
pause	(1)
play	('D-6')
pause	(32)
stop	('D-6', pause=16)
play	('D#6')
pause	(32)
stop	('D#6', pause=16)
c6(0x6)
song	(9)
halt	()
halt	()
compress()
