nop()
track	(0x7)
inst	(0x0)
c6(0x7)
volume	(100)
vol_range	(2)
play	('B-4', far=True)
pause	(32)
pause	(32)
pause	(32)
play	('A#4')
stop	('B-4')
pause	(32)
pause	(32)
pause	(20)
stop	('A#4')
play	('G-4')
stop	('G-4', pause=3)
play	('G#4')
stop	('G#4', pause=3)
play	('A-4')
stop	('A-4', pause=3)
play	('A#4')
stop	('A#4', pause=3)
play	('B-4')
pause	(32)
pause	(32)
stop	('B-4', pause=True)
vol_range	(3)
play	('F-4')
stop	('F-4', pause=3)
pause	(3)
play	('F-4')
stop	('F-4', pause=True)
pause	(3)
play	('F-5')
stop	('F-5', pause=True)
pause	(3)
play	('F-4')
stop	('F-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('F-5')
stop	('F-5', pause=6)
play	('F-4')
stop	('F-4', pause=6)
play	('F-3')
stop	('F-3', pause=True)
pause	(9)
play	('F-4')
stop	('F-4', pause=3)
pause	(3)
play	('F-5')
stop	('F-5', pause=True)
pause	(3)
play	('F-4')
stop	('F-4', pause=True)
pause	(3)
play	('F-5')
stop	('F-5', pause=6)
play	('F-4')
stop	('F-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
vol_range	(2)
play	('B-4')
pause	(32)
pause	(32)
stop	('B-4', pause=True)
play	('A#4')
pause	(32)
pause	(32)
stop	('A#4', pause=20)
play	('G-4')
stop	('G-4', pause=3)
play	('G#4')
stop	('G#4', pause=3)
play	('A-4')
stop	('A-4', pause=3)
play	('A#4')
stop	('A#4', pause=3)
play	('B-4')
pause	(32)
pause	(32)
stop	('B-4', pause=True)
vol_range	(3)
play	('F-4')
stop	('F-4', pause=3)
pause	(3)
play	('F-4')
stop	('F-4', pause=True)
pause	(3)
play	('F-5')
stop	('F-5', pause=True)
pause	(3)
play	('F-4')
stop	('F-4', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('F-5')
stop	('F-5', pause=6)
play	('F-4')
stop	('F-4', pause=6)
play	('F-3')
stop	('F-3', pause=True)
pause	(9)
play	('E-4')
stop	('E-4', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('B-4')
pause	(32)
stop	('B-4', pause=28)
play	('A-4')
stop	('A-4', pause=12)
play	('B-4')
stop	('B-4', pause=12)
play	('D-5')
pause	(32)
pause	(32)
stop	('D-5', pause=8)
play	('C-5')
stop	('C-5', pause=12)
play	('B-4')
stop	('B-4', pause=12)
play	('A-4')
stop	('A-4', pause=12)
play	('B-4')
stop	('B-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('B-4')
pause	(32)
stop	('B-4', pause=16)
play	('B-4')
stop	('B-4', pause=24)
play	('A-4')
stop	('A-4', pause=12)
play	('B-4')
stop	('B-4', pause=24)
play	('D-5')
stop	('D-5', pause=24)
play	('C-5')
stop	('C-5', pause=24)
play	('D-5')
stop	('D-5', pause=12)
play	('B-4')
pause	(32)
stop	('B-4', pause=28)
play	('A-4')
stop	('A-4', pause=12)
play	('B-4')
stop	('B-4', pause=12)
play	('D-5')
pause	(32)
pause	(32)
stop	('D-5', pause=8)
play	('C-5')
stop	('C-5', pause=24)
play	('D-5')
stop	('D-5', pause=12)
play	('E-5')
pause	(32)
stop	('E-5', pause=4)
vol_range	(2)
play	('C-5')
pause	(32)
stop	('C-5', pause=4)
vol_range	(3)
play	('G-4')
stop	('G-4', pause=4)
play	('A-4')
stop	('A-4', pause=4)
play	('B-4')
stop	('B-4', pause=4)
play	('C-5')
stop	('C-5', pause=4)
play	('D-5')
stop	('D-5', pause=4)
play	('E-5')
stop	('E-5', pause=4)
play	('F#5')
pause	(32)
pause	(32)
stop	('F#5', pause=8)
pause	(24)
c6(0x7)
inst	(0x1)
volume	(120)
play	('G-5')
pause	(32)
pause	(28)
play	('F#5')
stop	('G-5')
pause	(12)
stop	('F#5')
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
pause	(32)
stop	('B-5', pause=28)
play	('A-5')
stop	('A-5', pause=12)
play	('B-5')
stop	('B-5', pause=12)
play	('C-6')
pause	(32)
stop	('C-6', pause=4)
play	('B-5')
stop	('B-5', pause=24)
play	('A-5')
stop	('A-5', pause=24)
play	('G-5')
stop	('G-5', pause=24)
play	('A-5')
pause	(32)
stop	('A-5', pause=16)
play	('F#5')
pause	(32)
stop	('F#5', pause=16)
halt	()
halt	()
compress()
