nop()
track	(0x4)
inst	(0x2)
c6(0x7)
volume	(105)
vol_range	(2)
play	('D-4', far=True)
pause	(6)
play	('E-4')
stop	('D-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('C#4')
stop	('C#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('G-4')
stop	('G-4', pause=12)
play	('D#5')
stop	('D#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
play	('G-4')
stop	('G-4', pause=12)
play	('D#4')
stop	('D#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('F-5')
stop	('F-5', pause=12)
play	('C-5')
stop	('C-5', pause=12)
play	('F-5')
stop	('F-5', pause=12)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
vol_range	(3)
play	('D-4')
stop	('D-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('C#4')
stop	('C#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('G-4')
stop	('G-4', pause=12)
play	('D#5')
stop	('D#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-4')
stop	('G-4', pause=12)
play	('G-4')
stop	('G-4', pause=12)
vol_range	(3)
play	('D#4')
stop	('D#4', pause=True)
vol_range	(2)
play	('G-4')
stop	('G-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('D-4')
stop	('D-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
vol_range	(3)
play	('F-4')
stop	('F-4', pause=True)
vol_range	(2)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
pause	(32)
pause	(10)
play	('D-4')
stop	('D-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('G-4')
stop	('G-4', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('B-4')
stop	('B-4', pause=12)
play	('A-4')
stop	('A-4', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
vol_range	(3)
play	('D-4')
stop	('D-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('G-4')
stop	('G-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=12)
vol_range	(2)
play	('F#4')
stop	('F#4', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
vol_range	(3)
play	('D-4')
stop	('D-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(2)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
play	('E-4')
stop	('E-4', pause=6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=12)
play	('C-5')
stop	('C-5', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('G-4')
stop	('G-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('G-4')
stop	('G-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
vol_range	(3)
play	('F#5')
stop	('F#5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
vol_range	(3)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
play	('B-4')
stop	('B-4', pause=6)
vol_range	(3)
play	('G-5')
stop	('G-5', pause=6)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('D#5')
stop	('D#5', pause=6)
halt	()
halt	()
compress()
