nop()
track	(0x1)
inst	(0x1)
c6(0x7)
volume	(60)
pause	(24)
vol_range	(3)
play	('F-4', far=True)
stop	('F-4', pause=3)
play	('G-4')
stop	('G-4', pause=3)
play	('A-4')
stop	('A-4', pause=3)
play	('A#4')
stop	('A#4', pause=3)
play	('C-5')
stop	('C-5', pause=3)
play	('D-5')
stop	('D-5', pause=3)
play	('D#5')
stop	('D#5', pause=3)
play	('E-5')
stop	('E-5', pause=3)
play	('F-5')
stop	('F-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=3)
play	('D#5')
stop	('D#5', pause=3)
play	('E-5')
stop	('E-5', pause=3)
play	('F-5')
stop	('F-5', pause=3)
play	('G-5')
stop	('G-5', pause=3)
vol_range	(3)
play	('G#5')
stop	('G#5', pause=3)
play	('A-5')
stop	('A-5', pause=3)
play	('A#5')
stop	('A#5', pause=3)
play	('C-6')
pause	(32)
pause	(32)
stop	('C-6', pause=8)
halt	()
halt	()
compress()
