nop()
track	(0x3)
inst	(0x5)
c6(0x7)
volume	(95)
vol_range	(3)
play	('C-6', far=True)
stop	('C-6', pause=8)
pause	(8)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=24)
play	('A#5')
stop	('A#5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=24)
vol_range	(3)
play	('C-6')
stop	('C-6', pause=24)
play	('A#5')
stop	('A#5', pause=24)
play	('F-5')
stop	('F-5', pause=24)
pause	(12)
play	('C-6')
stop	('C-6', pause=4)
play	('D-6')
stop	('D-6', pause=4)
play	('E-6')
stop	('E-6', pause=4)
play	('C-6')
stop	('C-6', pause=8)
play	('C-6')
stop	('C-6', pause=8)
play	('C-6')
stop	('C-6', pause=8)
play	('C-6')
stop	('C-6', pause=24)
halt	()
halt	()
compress()
