nop()
inst	(0x5)
c6(0x7)
volume	(120)
vol_range	(3)
play	('C-5', far=True)
pause	(12)
play	('D-5')
stop	('C-5')
pause	(6)
stop	('D-5')
play	('D#5')
stop	('D#5', pause=True)
play	('E-5')
stop	('E-5', pause=12)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=24)
play	('D-6')
stop	('D-6', pause=24)
play	('C-6')
stop	('C-6', pause=24)
play	('D#6')
stop	('D#6', pause=24)
play	('D-6')
stop	('D-6', pause=24)
play	('A#5')
stop	('A#5', pause=24)
play	('C-6')
stop	('C-6', pause=24)
play	('F-6')
stop	('F-6', pause=8)
play	('F-6')
stop	('F-6', pause=8)
play	('F-6')
stop	('F-6', pause=8)
play	('E-6')
stop	('E-6', pause=24)
halt	()
halt	()
