nop()
track	(0x2)
inst	(0x2)
c6(0x7)
volume	(110)
vol_range	(3)
play	('C-5', far=True)
stop	('C-5', pause=18)
pause	(6)
play	('C-5')
stop	('C-5', pause=8)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=8)
play	('C-5')
stop	('C-5', pause=8)
vol_range	(3)
play	('A#4')
stop	('A#4', pause=24)
vol_range	(2)
play	('A#4')
stop	('A#4', pause=8)
play	('A#4')
stop	('A#4', pause=8)
play	('A#4')
stop	('A#4', pause=8)
play	('C-5')
stop	('C-5', pause=24)
play	('D#5')
stop	('D#5', pause=24)
play	('D-5')
stop	('D-5', pause=24)
play	('A#4')
stop	('A#4', pause=24)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=18)
pause	(6)
play	('C-5')
stop	('C-5', pause=8)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=8)
play	('C-5')
stop	('C-5', pause=8)
vol_range	(3)
play	('C-5')
stop	('C-5', pause=24)
halt	()
halt	()
compress()
