nop()
track	(0x9)
inst	(0x3)
c6(0x7)
volume	(80)
vol_range	(3)
play	('F-5', far=True)
stop	('F-5', pause=8)
pause	(13)
vol_range	(2)
play	('F-5')
pause	(3)
vol_range	(3)
play	('F-5')
stop	('F-5', pause=5)
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
pause	(16)
play	('F-5')
stop	('F-5', pause=8)
pause	(8)
play	('F-5')
stop	('F-5', pause=True)
vol_range	(2)
play	('F-5')
stop	('F-5', pause=True)
vol_range	(3)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
vol_range	(2)
play	('F-5')
stop	('F-5', pause=True)
vol_range	(3)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
vol_range	(2)
play	('F-5')
pause	(4)
play	('F-5')
stop	('F-5', pause=True)
vol_range	(3)
play	('F-5')
stop	('F-5', pause=1)
stop	('F-5', pause=True)
pause	(3)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
pause	(16)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
play	('F-5')
stop	('F-5', pause=8)
halt	()
halt	()
compress()
