nop()
track	(0x9)
inst	(0x3)
c6(0x7)
volume	(90)
pause	(32)
pause	(10)
vol_range	(2)
play	('A#4', far=True)
stop	('A#4', pause=3)
play	('A#4')
stop	('A#4', pause=3)
play	('A#4')
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
vol_range	(3)
play	('A#4')
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
halt	()
halt	()
compress()
