nop()
inst	(0x3)
c6(0x7)
vol_range	(2)
play	('G#4', far=True)
volume	(90)
stop	('G#4', pause=9)
pause	(15)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4')
pause	(6)
play	('G#4')
stop	('G#4', pause=1)
pause	(17)
play	('G#4')
stop	('G#4', pause=10)
pause	(14)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(9)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=6)
pause	(12)
play	('G#4')
stop	('G#4', pause=5)
pause	(19)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(2)
play	('G#4')
stop	('G#4', pause=5)
pause	(7)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(20)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=1)
pause	(5)
play	('G#4')
stop	('G#4', pause=9)
pause	(15)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4')
pause	(6)
play	('G#4')
stop	('G#4', pause=1)
pause	(17)
play	('G#4')
stop	('G#4', pause=10)
pause	(14)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(9)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=6)
pause	(12)
play	('G#4')
stop	('G#4', pause=5)
pause	(19)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(2)
play	('G#4')
stop	('G#4', pause=5)
pause	(7)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(20)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=1)
pause	(5)
play	('G#4')
stop	('G#4', pause=9)
pause	(15)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4')
pause	(6)
play	('G#4')
stop	('G#4', pause=1)
pause	(17)
play	('G#4')
stop	('G#4', pause=10)
pause	(14)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(9)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=6)
pause	(12)
play	('G#4')
stop	('G#4', pause=5)
pause	(19)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(2)
play	('G#4')
stop	('G#4', pause=5)
pause	(7)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(20)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=1)
pause	(5)
play	('G#4')
stop	('G#4', pause=9)
pause	(15)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4')
pause	(6)
play	('G#4')
stop	('G#4', pause=1)
pause	(17)
play	('G#4')
stop	('G#4', pause=10)
pause	(14)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(9)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=6)
pause	(12)
play	('G#4')
stop	('G#4', pause=5)
pause	(19)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(2)
play	('G#4')
stop	('G#4', pause=5)
pause	(7)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(20)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=1)
pause	(5)
play	('G#4')
stop	('G#4', pause=9)
pause	(15)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4')
pause	(6)
play	('G#4')
stop	('G#4', pause=1)
pause	(17)
play	('G#4')
stop	('G#4', pause=10)
pause	(14)
play	('G#4')
stop	('G#4', pause=2)
pause	(4)
play	('G#4')
stop	('G#4', pause=5)
pause	(13)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(9)
play	('G#4')
stop	('G#4', pause=3)
pause	(9)
play	('G#4')
stop	('G#4', pause=6)
pause	(12)
play	('G#4')
stop	('G#4', pause=5)
pause	(19)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(2)
play	('G#4')
stop	('G#4', pause=5)
pause	(7)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=True)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=4)
pause	(20)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(14)
play	('G#4')
stop	('G#4', pause=3)
pause	(3)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=4)
pause	(8)
play	('G#4')
stop	('G#4', pause=1)
pause	(5)
c6(0x6)
song	(21)
halt	()
halt	()
compress()
