nop()
track	(0x1)
inst	(0x2)
c6(0x7)
volume	(115)
vol_range	(2)
play	('B-4', far=True)
pause	(12)
play	('B-4')
stop	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
halt	()
halt	()
compress()
