nop()
track	(0x1)
inst	(0x2)
c6(0x7)
volume	(105)
vol_range	(3)
play	('D-4', far=True)
pause	(6)
play	('D-4')
stop	('D-4')
stop	('D-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(18)
play	('C-4')
stop	('C-4', pause=6)
play	('C-4')
stop	('C-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-4')
stop	('C-4', pause=6)
play	('D#4')
stop	('D#4', pause=6)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('C-4')
stop	('C-4', pause=True)
play	('B-3')
stop	('B-3', pause=True)
play	('C-4')
stop	('C-4', pause=True)
pause	(6)
play	('A-3')
stop	('A-3', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('G-4')
stop	('G-4', pause=True)
pause	(6)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-3')
stop	('A-3', pause=True)
pause	(18)
play	('A-3')
stop	('A-3', pause=6)
play	('A-3')
stop	('A-3', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-3')
stop	('A-3', pause=6)
play	('G-4')
stop	('G-4', pause=6)
pause	(6)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-3')
stop	('A-3', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('B-3')
stop	('B-3', pause=True)
play	('C#4')
stop	('C#4', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('F-4')
stop	('F-4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(18)
play	('C-4')
stop	('C-4', pause=6)
play	('C-4')
stop	('C-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-4')
stop	('C-4', pause=6)
play	('D#4')
stop	('D#4', pause=6)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('C-4')
stop	('C-4', pause=True)
play	('B-3')
stop	('B-3', pause=True)
play	('C-4')
stop	('C-4', pause=True)
pause	(6)
play	('A-3')
stop	('A-3', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('G-4')
stop	('G-4', pause=True)
pause	(6)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-3')
stop	('A-3', pause=True)
pause	(18)
play	('A-3')
stop	('A-3', pause=6)
play	('A-3')
stop	('A-3', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-3')
stop	('A-3', pause=6)
play	('G-4')
stop	('G-4', pause=6)
pause	(6)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('D#4')
stop	('D#4', pause=True)
pause	(6)
play	('F#4')
stop	('F#4', pause=3)
play	('F-4')
stop	('F-4', pause=3)
play	('E-4')
stop	('E-4', pause=3)
play	('D#4')
stop	('D#4', pause=3)
halt	()
halt	()
compress()
