nop()
track	(0x9)
inst	(0x3)
vol_range	(3)
play	('C-3', far=True)
c6(0x7)
volume	(110)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=12)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=12)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=3)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=3)
play	('A-8')
stop	('A-8', pause=3)
vol_range	(1)
play	('A-8')
stop	('A-8', pause=3)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=12)
play	('A-8')
stop	('A-8', pause=12)
play	('C-3', far=True)
stop	('C-3', pause=24)
play	('A#4', far=True)
stop	('A#4', pause=24)
halt	()
halt	()
compress()
