nop()
track	(0x5)
inst	(0x2)
vol_range	(3)
play	('D-5', far=True)
c6(0x7)
volume	(110)
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=12)
play	('G#5')
stop	('G#5', pause=3)
play	('A-5')
stop	('A-5', pause=3)
play	('G#5')
stop	('G#5', pause=3)
play	('G-5')
stop	('G-5', pause=3)
play	('D#5')
stop	('D#5', pause=True)
pause	(6)
play	('C#6')
stop	('C#6', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
pause	(18)
play	('D-5')
stop	('D-5', pause=6)
halt	()
halt	()
