nop()
track	(0x2)
inst	(0x0)
vol_range	(3)
play	('A-4', far=True)
c6(0x7)
volume	(100)
stop	('A-4', pause=3)
pause	(9)
play	('E-5')
stop	('E-5', pause=12)
play	('C-5')
stop	('C-5', pause=3)
pause	(32)
pause	(1)
play	('B-4')
stop	('B-4', pause=3)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('B-4')
stop	('B-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('G-4')
stop	('G-4', pause=12)
halt	()
halt	()
