nop()
track	(0x9)
inst	(0x3)
c6(0x7)
volume	(110)
pause	(32)
pause	(16)
vol_range	(3)
play	('A#4', far=True)
pause	(6)
play	('A#4')
stop	('A#4', pause=4)
stop	('A#4', pause=2)
play	('D-4')
stop	('D-4', pause=12)
play	('A#4')
stop	('A#4', pause=12)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(1)
play	('A-8', far=True)
stop	('A-8', pause=12)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(1)
play	('A-8', far=True)
stop	('A-8', pause=12)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(1)
play	('A-8', far=True)
stop	('A-8', pause=12)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(1)
play	('A-8', far=True)
stop	('A-8', pause=12)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(1)
play	('A-8', far=True)
stop	('A-8', pause=12)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A#4')
stop	('A#4', pause=12)
play	('A#4')
stop	('A#4', pause=12)
halt	()
halt	()
compress()
