E = 1

TM_ON_LOGO = 1
TIGHT_DRAW_SPACING = 0
FIXED_MECHA_BOMBER_PALETTES = 1
NEW_MAIN_MENU_COLORS = 1
WESTERN_MOGUCHAN_PALETTE = 1
WESTERN_MOGUCHAN_GRAPHIC = 1
NEW_VICTORY_PALETTES = 1
USE_KATAKANA = 0
DISPLAY_LICENSED_BY = 1
USE_MULTI5_BIOS = 1
SHOW_INTRODUCTION = 0
FIX_CREDITS_GRAMMAR = 1
COUNTRY_CODE = 2 ; PAL
FALLING_BOMBERMEN_DRAW = 0
TRADEMARK_LINE = 1
FPS = 50
FIX_JOYPAD_5_BUG = 1
SHORT_GAMEOVER_BRANCH = 0
JOYPAD_RELATED_BUGFIX = 1
FORBID_INTRO_SKIP = 1

; Some addressing modes were changed in the localizations
define az a
define az2 a

; Original bug fixes and features
FIXED_KURO_VICTORY_PALETTE = 0
FIXED_OVERLAY_PALETTES = 0
