.DEFINE J TRUE

TM_ON_LOGO = 0
TIGHT_DRAW_SPACING = 1
FIXED_MECHA_BOMBER_PALETTES = 0
NEW_MAIN_MENU_COLORS = 0
WESTERN_MOGUCHAN_PALETTE = 0
WESTERN_MOGUCHAN_GRAPHIC = 0
NEW_VICTORY_PALETTES = 0
USE_KATAKANA = 1
DISPLAY_LICENSED_BY = 0
USE_MULTI5_BIOS = 0
SHOW_INTRODUCTION = 1
FIX_CREDITS_GRAMMAR = 0
COUNTRY_CODE = 0 ; NTSC 0
FALLING_BOMBERMEN_DRAW = 1
TRADEMARK_LINE = 0
FPS = 60
FIX_JOYPAD_5_BUG = 0
SHORT_GAMEOVER_BRANCH = 1
JOYPAD_RELATED_BUGFIX = 0

; Some addressing modes were changed in the localizations
.DEFINE AZ z:
.DEFINE AZ2 z:

; Original bug fixes and features
FIXED_KURO_VICTORY_PALETTE = 0
FIXED_OVERLAY_PALETTES = 0