nop()
inst	(0x4)
c6(0x7)
volume	(100)
vol_range	(2)
play	('B-3', far=True)
pause	(12)
vol_range	(3)
play	('E-4')
stop	('B-3')
stop	('E-4', pause=True)
play	('G#4')
stop	('G#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
vol_range	(2)
play	('G-4')
stop	('G-4', pause=True)
play	('D#4')
stop	('D#4', pause=True)
play	('A#3')
stop	('A#3', pause=True)
play	('A-3')
stop	('A-3', pause=True)
vol_range	(3)
play	('D-4')
stop	('D-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G#4')
pause	(24)
volume	(80)
pause	(3)
volume	(60)
pause	(3)
volume	(40)
pause	(6)
volume	(20)
stop	('G#4', pause=12)
halt	()
halt	()
