nop()
track	(0x2)
inst	(0x4)
c6(0x7)
volume	(100)
vol_range	(3)
play	('E-5', far=True)
pause	(12)
play	('G#5')
stop	('E-5')
stop	('G#5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('D#6')
stop	('D#6', pause=True)
play	('C#6')
stop	('C#6', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('B-5')
pause	(32)
stop	('B-5', pause=16)
halt	()
halt	()
