nop()
track	(0x5)
inst	(0x2)
c6(0x7)
volume	(100)
vol_range	(3)
play	('G-4', far=True)
pause	(12)
play	('G-4')
stop	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
vol_range	(2)
play	('F#5')
stop	('F#5', pause=True)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=24)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=True)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
pause	(12)
play	('E-4')
stop	('E-4', pause=24)
play	('E-4')
stop	('E-4', pause=True)
vol_range	(2)
play	('F#4')
stop	('F#4', pause=True)
pause	(12)
vol_range	(3)
play	('G-4')
pause	(32)
stop	('G-4', pause=4)
play	('A#4')
stop	('A#4', pause=24)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=24)
play	('G-4')
stop	('G-4', pause=24)
play	('D-5')
pause	(32)
pause	(32)
stop	('D-5', pause=8)
halt	()
halt	()
compress()
