nop()
track	(0x3)
inst	(0x4)
c6(0xa)
c6(0x7)
volume	(85)
pan	(20)
pause	(12)
vol_range	(3)
play	('D-5', far=True)
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
vol_range	(2)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
vol_range	(1)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('E-4')
stop	('C#5', pause=True)
stop	('E-4')
vol_range	(2)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('E-5')
play	('G-4')
stop	('E-5', pause=True)
stop	('G-4')
vol_range	(2)
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
vol_range	(1)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
vol_range	(2)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
vol_range	(1)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('E-4')
stop	('C#5', pause=True)
stop	('E-4')
vol_range	(2)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('E-5')
play	('G-4')
stop	('E-5', pause=True)
stop	('G-4')
vol_range	(2)
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
vol_range	(1)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
vol_range	(2)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
vol_range	(1)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('E-4')
stop	('C#5', pause=True)
stop	('E-4')
vol_range	(2)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('E-5')
play	('G-4')
stop	('E-5', pause=True)
stop	('G-4')
vol_range	(2)
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
vol_range	(1)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
vol_range	(2)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
vol_range	(1)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('E-4')
stop	('C#5', pause=True)
stop	('E-4')
vol_range	(2)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('E-5')
play	('G-4')
stop	('E-5', pause=True)
stop	('G-4')
vol_range	(2)
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
vol_range	(1)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
vol_range	(2)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
vol_range	(1)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('E-4')
stop	('C#5', pause=True)
stop	('E-4')
vol_range	(2)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('E-5')
play	('G-4')
stop	('E-5', pause=True)
stop	('G-4')
vol_range	(2)
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
vol_range	(1)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
vol_range	(2)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
vol_range	(1)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('E-4')
stop	('C#5', pause=True)
stop	('E-4')
vol_range	(2)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('E-5')
play	('G-4')
stop	('E-5', pause=True)
stop	('G-4')
vol_range	(2)
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
vol_range	(1)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
vol_range	(2)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
vol_range	(1)
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('C#5')
play	('E-4')
stop	('C#5', pause=True)
stop	('E-4')
vol_range	(2)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('E-5')
play	('G-4')
stop	('E-5', pause=True)
stop	('G-4')
vol_range	(2)
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
vol_range	(1)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('A-4')
vol_range	(2)
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('E-4')
stop	('A-4', pause=True)
stop	('E-4')
pause	(12)
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('B-4')
stop	('D-5', pause=True)
stop	('B-4')
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
vol_range	(3)
play	('F-5')
play	('B-4')
stop	('F-5', pause=True)
stop	('B-4')
vol_range	(2)
play	('E-5')
play	('B-4')
stop	('E-5', pause=True)
stop	('B-4')
pause	(12)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
vol_range	(3)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
vol_range	(2)
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(12)
play	('A-4')
play	('F#4')
stop	('A-4', pause=True)
stop	('F#4')
play	('B-4')
play	('G-4')
stop	('B-4', pause=True)
stop	('G-4')
pause	(12)
play	('B-4')
play	('G-4')
pause	(24)
stop	('B-4')
stop	('G-4')
play	('B-4')
play	('G-4')
pause	(12)
stop	('B-4')
stop	('G-4')
vol_range	(3)
play	('C#5')
play	('A-4')
stop	('C#5', pause=True)
stop	('A-4')
pause	(12)
play	('D-5')
play	('B-4')
pause	(24)
stop	('D-5')
stop	('B-4')
play	('C#5')
play	('A-4')
pause	(12)
stop	('C#5')
stop	('A-4')
play	('B-4')
vol_range	(2)
play	('G-4')
stop	('B-4', pause=True)
stop	('G-4')
play	('G-4')
play	('D-4')
stop	('G-4', pause=True)
stop	('D-4')
play	('D-4')
play	('A#3')
stop	('D-4', pause=True)
stop	('A#3')
vol_range	(3)
play	('A#4')
vol_range	(2)
play	('G-4')
stop	('A#4', pause=True)
stop	('G-4')
play	('A-4')
play	('F#4')
stop	('A-4', pause=True)
stop	('F#4')
play	('G-4')
play	('E-4')
stop	('G-4', pause=True)
stop	('E-4')
play	('F#4')
play	('D-4')
pause	(32)
pause	(32)
stop	('F#4', pause=True)
stop	('D-4')
halt	()
halt	()
compress()
