nop()
track	(0x3)
inst	(0x0)
c6(0xa)
c6(0x7)
pan	(40)
volume	(100)
vol_range	(3)
play	('D-4', far=True)
stop	('D-4', pause=5)
pause	(1)
play	('D-4')
stop	('D-4', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-4')
stop	('D-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('B-4')
pause	(32)
stop	('B-4', pause=16)
halt	()
halt	()
