nop()
track	(0x4)
inst	(0x5)
c6(0xa)
c6(0x7)
pan	(80)
volume	(105)
vol_range	(3)
play	('F#5', far=True)
play	('A-5')
play	('D-6')
pause	(5)
stop	('F#5')
stop	('D-6')
stop	('A-5')
pause	(1)
play	('D-6')
play	('A-5')
play	('F#5')
pause	(6)
stop	('D-6')
stop	('F#5')
stop	('A-5')
play	('D-7', far=True)
play	('A-6')
play	('F#6')
stop	('D-7', pause=True)
stop	('F#6')
stop	('A-6')
play	('D-6')
play	('A-5')
play	('F#5')
stop	('D-6', pause=True)
stop	('F#5')
stop	('A-5')
play	('F#6')
play	('D-6')
play	('A-5')
stop	('F#6', pause=True)
stop	('A-5')
stop	('D-6')
pause	(6)
play	('A-6')
play	('F#6')
play	('D-6')
stop	('A-6', pause=True)
stop	('D-6')
stop	('F#6')
play	('B-6')
play	('F#6')
play	('D-6')
stop	('B-6', pause=True)
stop	('D-6')
stop	('F#6')
play	('A-6')
play	('F#6')
play	('D-6')
stop	('A-6', pause=True)
stop	('D-6')
stop	('F#6')
pause	(6)
play	('A-6')
play	('F#6')
play	('D-6')
stop	('A-6', pause=True)
stop	('D-6')
stop	('F#6')
pause	(6)
play	('G-6')
play	('F-6')
play	('D-6')
pause	(32)
pause	(16)
stop	('G-6')
stop	('D-6')
stop	('F-6')
halt	()
halt	()
compress()

data += "\xFF" # No clue why it's there. Plays fine without it.