nop()
track	(0x2)
inst	(0x2)
c6(0x7)
volume	(115)
vol_range	(3)
play	('C-5', far=True)
stop	('C-5', pause=3)
pause	(3)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
vol_range	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
vol_range	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
vol_range	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
vol_range	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-5')
stop	('C-5', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('C-6')
stop	('C-6', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(2)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
vol_range	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
vol_range	(2)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
vol_range	(2)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
vol_range	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-4')
stop	('A-4', pause=True)
pause	(3)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
vol_range	(2)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
vol_range	(3)
play	('G-5')
stop	('G-5', pause=True)
pause	(3)
play	('G-5')
stop	('G-5', pause=True)
pause	(3)
play	('E-5')
stop	('E-5', pause=True)
pause	(3)
play	('E-5')
stop	('E-5', pause=True)
pause	(3)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(3)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
play	('F-5')
stop	('F-5', pause=6)
pause	(18)
play	('A-5')
stop	('A-5', pause=12)
play	('B-5')
stop	('B-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=12)
play	('C-5')
stop	('C-5', pause=12)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('B-4')
stop	('B-4', pause=6)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(3)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
pause	(18)
play	('A-5')
stop	('A-5', pause=12)
play	('B-5')
stop	('B-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=12)
play	('C-5')
stop	('C-5', pause=12)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('B-4')
stop	('B-4', pause=6)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(6)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(2)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(3)
play	('E-6')
stop	('E-6', pause=12)
play	('E-5')
stop	('E-5', pause=12)
play	('G-5')
stop	('G-5', pause=True)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('C#6')
stop	('C#6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(2)
play	('C#6')
stop	('C#6', pause=6)
pause	(18)
play	('C#6')
stop	('C#6', pause=12)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=6)
pause	(6)
vol_range	(2)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(2)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(3)
play	('E-6')
stop	('E-6', pause=12)
play	('E-5')
stop	('E-5', pause=12)
play	('G-5')
stop	('G-5', pause=True)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('C#6')
stop	('C#6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
play	('C#6')
stop	('C#6', pause=6)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('G-5')
stop	('G-5', pause=12)
play	('E-5')
stop	('E-5', pause=12)
pause	(12)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
vol_range	(3)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
pause	(18)
play	('A-5')
stop	('A-5', pause=12)
play	('B-5')
stop	('B-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=12)
play	('C-5')
stop	('C-5', pause=12)
vol_range	(2)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
vol_range	(3)
play	('B-5')
stop	('B-5', pause=12)
play	('B-4')
stop	('B-4', pause=12)
play	('B-4')
stop	('B-4', pause=12)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(3)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
play	('F-5')
stop	('F-5', pause=6)
pause	(18)
play	('A-5')
stop	('A-5', pause=12)
play	('B-5')
stop	('B-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=12)
play	('C-5')
stop	('C-5', pause=12)
vol_range	(2)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
vol_range	(3)
play	('B-5')
stop	('B-5', pause=12)
play	('B-4')
stop	('B-4', pause=12)
play	('B-4')
stop	('B-4', pause=12)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(2)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(3)
play	('E-6')
stop	('E-6', pause=12)
play	('E-5')
stop	('E-5', pause=12)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('C#6')
stop	('C#6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
vol_range	(2)
play	('C#6')
stop	('C#6', pause=6)
pause	(18)
play	('C#6')
stop	('C#6', pause=12)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=6)
pause	(6)
vol_range	(2)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(2)
play	('E-5')
stop	('E-5', pause=12)
vol_range	(3)
play	('E-6')
stop	('E-6', pause=12)
play	('E-5')
stop	('E-5', pause=12)
play	('G-5')
stop	('G-5', pause=True)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('C#6')
stop	('C#6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-6')
stop	('D-6', pause=12)
play	('D-5')
stop	('D-5', pause=12)
play	('C#6')
stop	('C#6', pause=12)
halt	()
halt	()
compress()

data += "\x80" # No clue why it's there. Plays fine without it.