nop()
track	(0x4)
inst	(0x0)
c6(0xa)
c6(0x7)
pan	(85)
volume	(75)
pause	(255, set=False)
pause	(32)
pause	(13)
vol_range	(3)
play	('E-6', far=True)
stop	('E-6', pause=6)
pause	(6)
play	('D-6')
stop	('D-6', pause=4)
play	('E-6')
stop	('E-6', pause=4)
play	('D-6')
stop	('D-6', pause=4)
play	('B-5')
stop	('B-5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
pause	(255, set=False)
pause	(32)
pause	(19)
play	('E-6')
stop	('E-6', pause=6)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
pause	(6)
play	('G-6')
stop	('G-6', pause=True)
pause	(6)
play	('E-6')
stop	('E-6', pause=True)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('E-6')
stop	('E-6', pause=True)
pause	(255, set=False)
pause	(255, set=False)
pause	(255, set=False)
pause	(21)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
pause	(18)
play	('A-5')
stop	('A-5', pause=12)
play	('B-5')
stop	('B-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(18)
play	('C-5')
stop	('C-5', pause=12)
play	('B-5')
stop	('B-5', pause=6)
pause	(18)
play	('B-4')
stop	('B-4', pause=6)
pause	(30)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
play	('D-5')
stop	('D-5', pause=12)
play	('D-6')
stop	('D-6', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=12)
play	('F-5')
stop	('F-5', pause=True)
pause	(18)
play	('A-5')
stop	('A-5', pause=12)
play	('B-5')
stop	('B-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(18)
play	('C-5')
stop	('C-5', pause=12)
play	('B-5')
stop	('B-5', pause=6)
pause	(18)
play	('B-4')
stop	('B-4', pause=6)
pause	(30)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('E-5')
stop	('E-5', pause=12)
play	('E-6')
stop	('E-6', pause=True)
pause	(6)
play	('E-5')
stop	('E-5', pause=12)
play	('G-5')
stop	('G-5', pause=True)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('C#6')
stop	('C#6', pause=12)
play	('D-6')
stop	('D-6', pause=6)
pause	(18)
play	('D-5')
stop	('D-5', pause=12)
play	('C#6')
stop	('C#6', pause=6)
pause	(18)
play	('C#5')
stop	('C#5', pause=6)
pause	(30)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('E-5')
stop	('E-5', pause=12)
play	('E-6')
stop	('E-6', pause=True)
pause	(6)
play	('E-5')
stop	('E-5', pause=12)
play	('G-5')
stop	('G-5', pause=True)
pause	(18)
play	('B-5')
stop	('B-5', pause=12)
play	('C#6')
stop	('C#6', pause=12)
play	('D-6')
stop	('D-6', pause=6)
pause	(18)
play	('D-5')
stop	('D-5', pause=12)
play	('C#6')
stop	('C#6', pause=6)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
halt	()
halt	()
compress()
