nop()
track	(0x5)
inst	(0x2)
c6(0x7)
volume	(95)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
pause	(32)
vol_range	(3)
play	('D-5', far=True)
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
pause	(32)
pause	(32)
pause	(32)
pause	(24)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(12)
play	('A-4')
stop	('A-4', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
pause	(12)
play	('D-6')
stop	('D-6', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(12)
play	('A-4')
stop	('A-4', pause=6)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('D-5')
pause	(32)
pause	(32)
stop	('D-5', pause=True)
halt	()
halt	()
compress()
