nop()
track	(0x6)
inst	(0x4)
c6(0x7)
c6(0xa)
vol_range	(2)
play	('A-3', far=True)
volume	(90)
pan	(110)
stop	('A-3', pause=3)
play	('A#3')
stop	('A#3', pause=3)
play	('B-3')
stop	('B-3', pause=3)
play	('C#4')
stop	('C#4', pause=3)
play	('D-4')
stop	('D-4', pause=3)
play	('E-4')
stop	('E-4', pause=3)
play	('F#4')
stop	('F#4', pause=3)
play	('G-4')
stop	('G-4', pause=3)
play	('G#4')
stop	('G#4', pause=3)
play	('A-4')
stop	('A-4', pause=3)
play	('B-4')
stop	('B-4', pause=3)
play	('C#5')
stop	('C#5', pause=3)
play	('D-5')
stop	('D-5', pause=3)
play	('E-5')
stop	('E-5', pause=3)
play	('F#5')
stop	('F#5', pause=3)
play	('G-5')
stop	('G-5', pause=3)
play	('A-5')
stop	('A-5', pause=3)
play	('B-5')
stop	('B-5', pause=3)
play	('C#6')
stop	('C#6', pause=3)
play	('D-6')
stop	('D-6', pause=3)
play	('D#6')
stop	('D#6', pause=3)
play	('E-6')
stop	('E-6', pause=3)
play	('F-6')
stop	('F-6', pause=3)
play	('F#6')
stop	('F#6', pause=3)
play	('G-5')
play	('G-4')
pause	(6)
stop	('G-5')
stop	('G-4')
play	('A-4')
play	('A-3')
stop	('A-4', pause=True)
stop	('A-3')
play	('C-5')
play	('C-4')
stop	('C-5', pause=True)
stop	('C-4')
play	('G-5', far=True)
play	('G-4')
stop	('G-5', pause=True)
stop	('G-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(6)
play	('A-4')
play	('F#4')
stop	('A-4', pause=True)
stop	('F#4')
pause	(6)
play	('G-4')
play	('E-4')
stop	('G-4', pause=True)
stop	('E-4')
pause	(6)
play	('A-4')
play	('F#4')
stop	('A-4', pause=True)
stop	('F#4')
pause	(6)
play	('F#4')
play	('D-4')
pause	(32)
pause	(16)
stop	('F#4')
stop	('D-4')
play	('D-5')
play	('F#4')
pause	(6)
stop	('D-5')
stop	('F#4')
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
play	('F#5')
stop	('F#5', pause=True)
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
play	('A-4')
play	('D-4')
stop	('A-4', pause=True)
stop	('D-4')
play	('A-5', far=True)
play	('D-5')
stop	('A-5', pause=True)
stop	('D-5')
play	('B-5')
play	('D-5')
stop	('B-5', pause=True)
stop	('D-5')
vol_range	(3)
play	('C-6')
vol_range	(2)
play	('F#5')
stop	('C-6', pause=True)
stop	('F#5')
play	('C-5')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
vol_range	(3)
play	('C-6', far=True)
vol_range	(2)
play	('F#5')
stop	('C-6', pause=True)
stop	('F#5')
play	('C-5')
play	('F#4')
stop	('C-5', pause=True)
stop	('F#4')
play	('G-5')
play	('G-4')
stop	('G-5', pause=True)
stop	('G-4')
play	('A-4')
play	('A-3')
stop	('A-4', pause=True)
stop	('A-3')
play	('C-5')
play	('C-4')
stop	('C-5', pause=True)
stop	('C-4')
play	('G-5', far=True)
play	('G-4')
stop	('G-5', pause=True)
stop	('G-4')
play	('D-5')
play	('A-4')
stop	('D-5', pause=True)
stop	('A-4')
pause	(6)
play	('A-4')
play	('F#4')
stop	('A-4', pause=True)
stop	('F#4')
pause	(6)
play	('G-4')
play	('E-4')
stop	('G-4', pause=True)
stop	('E-4')
pause	(6)
play	('A-4')
play	('F#4')
stop	('A-4', pause=True)
stop	('F#4')
pause	(6)
play	('F#4')
play	('D-4')
pause	(32)
pause	(16)
stop	('F#4')
stop	('D-4')
play	('D-5')
play	('F#4')
pause	(6)
stop	('D-5')
stop	('F#4')
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
play	('D-6', far=True)
play	('F#5')
stop	('D-6', pause=True)
stop	('F#5')
play	('D-5')
play	('F#4')
stop	('D-5', pause=True)
stop	('F#4')
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
stop	('A-4')
play	('A-4')
play	('D-4')
stop	('A-4', pause=True)
stop	('D-4')
play	('A-5', far=True)
play	('D-5')
stop	('A-5', pause=True)
stop	('D-5')
play	('B-5')
play	('D-5')
stop	('B-5', pause=True)
stop	('D-5')
vol_range	(3)
play	('C-6')
vol_range	(2)
play	('F#5')
stop	('C-6', pause=True)
stop	('F#5')
pause	(6)
vol_range	(3)
play	('C-6')
vol_range	(2)
play	('F#5')
stop	('C-6', pause=True)
stop	('F#5')
pause	(6)
play	('B-5')
play	('D-5')
pause	(24)
stop	('B-5')
stop	('D-5')
play	('G-4')
play	('E-4')
pause	(18)
stop	('G-4')
stop	('E-4')
play	('E-5')
stop	('E-5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('C-5')
play	('G-4')
pause	(6)
stop	('C-5')
stop	('G-4')
pause	(6)
play	('C-5')
play	('G-4')
stop	('C-5', pause=True)
stop	('G-4')
play	('B-4')
play	('G-4')
stop	('B-4', pause=True)
stop	('G-4')
play	('C-5')
play	('G-4')
stop	('C-5', pause=True)
stop	('G-4')
play	('B-4')
play	('G-4')
stop	('B-4', pause=True)
stop	('G-4')
play	('G-4')
play	('E-4')
stop	('G-4', pause=True)
stop	('E-4')
play	('F#4')
play	('D-4')
pause	(18)
stop	('F#4')
stop	('D-4')
play	('F#5', far=True)
play	('D-5')
stop	('F#5', pause=True)
stop	('D-5')
play	('D-5')
pause	(32)
stop	('D-5', pause=28)
play	('G-4')
play	('E-4')
pause	(18)
stop	('G-4')
stop	('E-4')
play	('E-5')
stop	('E-5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('C-5')
play	('G-4')
pause	(6)
stop	('C-5')
stop	('G-4')
pause	(6)
play	('C-5')
play	('G-4')
stop	('C-5', pause=True)
stop	('G-4')
play	('B-4')
play	('G-4')
stop	('B-4', pause=True)
stop	('G-4')
play	('C-5')
play	('G-4')
stop	('C-5', pause=True)
stop	('G-4')
play	('B-4')
play	('G-4')
stop	('B-4', pause=True)
stop	('G-4')
play	('G-4')
play	('E-4')
stop	('G-4', pause=True)
stop	('E-4')
play	('F#4')
play	('D-4')
pause	(32)
pause	(32)
stop	('F#4', pause=True)
stop	('D-4')
halt	()
halt	()
compress()
