nop()
track	(0x3)
inst	(0x0)
c6(0x7)
volume	(85)
vol_range	(2)
play	('A-2', far=True)
pause	(3)
play	('A#2')
stop	('A-2')
stop	('A#2', pause=True)
play	('B-2')
stop	('B-2', pause=True)
play	('C#3')
stop	('C#3', pause=True)
play	('D-3')
stop	('D-3', pause=True)
play	('E-3')
stop	('E-3', pause=True)
play	('F#3')
stop	('F#3', pause=True)
play	('G-3')
stop	('G-3', pause=True)
play	('G#3')
stop	('G#3', pause=True)
play	('A-3')
stop	('A-3', pause=True)
play	('B-3')
stop	('B-3', pause=True)
play	('C#4')
stop	('C#4', pause=True)
play	('D-4')
stop	('D-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(3)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('A-4')
pause	(32)
pause	(32)
pause	(32)
stop	('A-4', pause=24)
vol_range	(2)
play	('G-5')
stop	('G-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
pause	(6)
vol_range	(3)
play	('A-4')
pause	(32)
pause	(32)
pause	(32)
stop	('A-4', pause=24)
pause	(24)
c6(0x7)
play	('C-5')
volume	(70)
stop	('C-5', pause=18)
play	('B-5')
stop	('B-5', pause=18)
play	('A-5')
pause	(32)
stop	('A-5', pause=28)
play	('A-4')
stop	('A-4', pause=18)
play	('B-5')
stop	('B-5', pause=18)
play	('A-5')
pause	(32)
stop	('A-5', pause=28)
play	('C-5')
stop	('C-5', pause=18)
play	('B-5')
stop	('B-5', pause=18)
play	('A-5')
pause	(32)
stop	('A-5', pause=28)
volume	(84)
vol_range	(2)
play	('F#5')
pause	(32)
pause	(2)
volume	(83)
pause	(1)
volume	(82)
pause	(1)
volume	(81)
pause	(1)
volume	(80)
pause	(1)
volume	(79)
pause	(1)
volume	(78)
pause	(1)
volume	(77)
pause	(1)
volume	(76)
pause	(1)
volume	(75)
pause	(1)
volume	(74)
pause	(1)
volume	(73)
pause	(1)
volume	(72)
pause	(1)
volume	(71)
pause	(1)
volume	(70)
pause	(1)
volume	(69)
pause	(1)
volume	(68)
pause	(1)
volume	(67)
pause	(1)
volume	(66)
pause	(1)
volume	(65)
pause	(1)
volume	(64)
pause	(2)
volume	(63)
pause	(1)
volume	(62)
pause	(1)
volume	(61)
pause	(1)
volume	(60)
pause	(1)
volume	(59)
pause	(1)
volume	(58)
pause	(1)
volume	(57)
pause	(1)
volume	(56)
pause	(1)
volume	(55)
pause	(1)
volume	(54)
pause	(1)
volume	(53)
pause	(1)
volume	(52)
pause	(1)
volume	(51)
pause	(1)
volume	(50)
pause	(1)
volume	(49)
pause	(1)
volume	(48)
pause	(1)
volume	(47)
pause	(1)
volume	(46)
pause	(1)
volume	(45)
pause	(1)
volume	(44)
pause	(2)
volume	(43)
pause	(1)
volume	(42)
pause	(1)
volume	(41)
pause	(1)
volume	(40)
pause	(1)
volume	(39)
pause	(1)
volume	(38)
pause	(1)
volume	(37)
pause	(1)
volume	(36)
pause	(1)
volume	(35)
pause	(1)
volume	(34)
pause	(1)
volume	(33)
pause	(1)
volume	(32)
pause	(1)
volume	(31)
pause	(1)
volume	(30)
pause	(1)
volume	(29)
pause	(1)
volume	(28)
pause	(1)
volume	(27)
pause	(1)
volume	(26)
pause	(1)
volume	(25)
pause	(1)
volume	(24)
stop	('F#5', pause=True)
halt	()
halt	()
compress()

data += "\xDA" # No clue why it's there. Plays fine without it.