nop()
track	(0x2)
inst	(0x5)
c6(0xa)
c6(0x7)
pan	(80)
volume	(100)
vol_range	(3)
play	('G-5', far=True)
stop	('G-5', pause=6)
play	('G-5')
play	('B-5')
pause	(6)
stop	('G-5')
stop	('B-5')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
pause	(30)
play	('F#5')
play	('D-6')
pause	(12)
stop	('F#5')
stop	('D-6')
pause	(12)
play	('G-5')
play	('E-6')
stop	('G-5', pause=True)
stop	('E-6')
pause	(32)
pause	(28)
play	('A-5')
play	('F#6')
pause	(12)
stop	('A-5')
stop	('F#6')
pause	(12)
play	('F#5')
play	('D-6')
stop	('F#5', pause=True)
stop	('D-6')
pause	(32)
pause	(32)
pause	(32)
pause	(12)
play	('G-5')
vol_range	(2)
play	('E-5')
stop	('G-5', pause=True)
stop	('E-5')
vol_range	(3)
play	('G-5')
play	('E-5')
stop	('G-5', pause=True)
stop	('E-5')
play	('A-5')
play	('F#5')
stop	('A-5', pause=True)
stop	('F#5')
play	('A-5')
play	('F#5')
pause	(24)
stop	('A-5')
stop	('F#5')
play	('B-5')
play	('G-6')
pause	(6)
stop	('B-5')
stop	('G-6')
play	('C-6')
play	('A-6')
stop	('C-6', pause=True)
stop	('A-6')
play	('B-5')
play	('G-6')
stop	('B-5', pause=True)
stop	('G-6')
play	('A-5')
play	('F#6')
stop	('A-5', pause=True)
stop	('F#6')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
play	('G-5')
play	('B-5')
stop	('G-5', pause=True)
stop	('B-5')
pause	(30)
play	('F#5')
play	('D-6')
pause	(12)
stop	('F#5')
stop	('D-6')
pause	(12)
play	('G-5')
play	('E-6')
stop	('G-5', pause=True)
stop	('E-6')
pause	(32)
pause	(28)
play	('A-5')
play	('F#6')
pause	(12)
stop	('A-5')
stop	('F#6')
pause	(12)
play	('F#5')
play	('D-6')
stop	('F#5', pause=True)
stop	('D-6')
pause	(32)
pause	(32)
pause	(32)
pause	(12)
play	('G-5')
play	('E-5')
stop	('G-5', pause=True)
stop	('E-5')
play	('G-5')
play	('E-5')
stop	('G-5', pause=True)
stop	('E-5')
play	('A-5')
play	('F#5')
stop	('A-5', pause=True)
stop	('F#5')
play	('A-5')
play	('F#5')
pause	(32)
pause	(4)
stop	('A-5')
stop	('F#5')
pause	(32)
pause	(28)
play	('G-6')
play	('B-6')
pause	(6)
stop	('G-6')
stop	('B-6')
pause	(32)
pause	(22)
vol_range	(2)
play	('F#6')
play	('D-6')
pause	(24)
stop	('F#6')
stop	('D-6')
vol_range	(3)
play	('G-6')
play	('E-6')
pause	(6)
stop	('G-6')
stop	('E-6')
pause	(32)
pause	(32)
pause	(2)
play	('D-6')
play	('G-6')
pause	(6)
stop	('D-6')
stop	('G-6')
pause	(18)
play	('C-6')
play	('E-6')
pause	(12)
stop	('C-6')
stop	('E-6')
play	('D-6')
play	('F#6')
pause	(6)
stop	('D-6')
stop	('F#6')
pause	(32)
pause	(32)
pause	(2)
play	('G-6')
vol_range	(2)
play	('C-6')
pause	(6)
stop	('G-6')
stop	('C-6')
vol_range	(3)
play	('A-6')
play	('D-6')
stop	('A-6', pause=True)
stop	('D-6')
play	('B-6')
play	('E-6')
stop	('B-6', pause=True)
stop	('E-6')
play	('C-7')
play	('F#6')
stop	('C-7', pause=True)
stop	('F#6')
play	('D-7')
play	('G-6')
stop	('D-7', pause=True)
stop	('G-6')
pause	(6)
play	('D-6')
vol_range	(2)
play	('G-6')
pause	(32)
pause	(4)
stop	('D-6')
stop	('G-6')
vol_range	(3)
play	('D-6')
play	('F#6')
pause	(6)
stop	('D-6')
stop	('F#6')
pause	(18)
play	('D-6')
play	('G-6')
pause	(12)
stop	('D-6')
stop	('G-6')
play	('E-6')
play	('G-6')
pause	(6)
stop	('E-6')
stop	('G-6')
play	('F#6')
play	('A-6')
stop	('F#6', pause=True)
stop	('A-6')
play	('G-6')
play	('B-6')
stop	('G-6', pause=True)
stop	('B-6')
pause	(32)
pause	(22)
play	('F#6')
play	('D-6')
pause	(24)
stop	('F#6')
stop	('D-6')
play	('G-6')
play	('E-6')
pause	(6)
stop	('G-6')
stop	('E-6')
pause	(32)
pause	(32)
pause	(26)
play	('B-5')
play	('D-6')
pause	(6)
stop	('B-5')
stop	('D-6')
play	('C-6')
play	('E-6')
stop	('C-6', pause=True)
stop	('E-6')
play	('D-6')
play	('F#6')
stop	('D-6', pause=True)
stop	('F#6')
pause	(32)
pause	(32)
pause	(2)
play	('G-6')
play	('C-6')
pause	(6)
stop	('G-6')
stop	('C-6')
play	('A-6')
play	('D-6')
stop	('A-6', pause=True)
stop	('D-6')
play	('B-6')
play	('E-6')
stop	('B-6', pause=True)
stop	('E-6')
play	('C-7')
play	('F#6')
stop	('C-7', pause=True)
stop	('F#6')
play	('D-6')
play	('F#6')
stop	('D-6', pause=True)
stop	('F#6')
pause	(6)
play	('D-6')
play	('F#6')
stop	('D-6', pause=True)
stop	('F#6')
pause	(6)
play	('D-6')
play	('F#6')
pause	(24)
stop	('D-6')
stop	('F#6')
play	('D-6')
play	('F#6')
pause	(18)
stop	('D-6')
stop	('F#6')
play	('E-6')
play	('G-6')
stop	('E-6', pause=True)
stop	('G-6')
play	('D-6')
play	('F#6')
pause	(4)
stop	('D-6')
stop	('F#6')
play	('E-6')
play	('G-6')
stop	('E-6', pause=True)
stop	('G-6')
play	('D-6')
play	('F#6')
stop	('D-6', pause=True)
stop	('F#6')
inst	(0x1)
c6(0x7)
volume	(110)
vol_range	(2)
play	('C-5', far=True)
play	('E-5')
pause	(24)
play	('G-4')
play	('B-4')
stop	('C-5')
stop	('E-5')
stop	('G-4', pause=True)
stop	('B-4')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('E-5')
play	('G-5')
stop	('E-5', pause=True)
stop	('G-5')
play	('D-5')
play	('F#5')
pause	(32)
pause	(16)
stop	('D-5')
stop	('F#5')
play	('F#5')
play	('D-5')
pause	(12)
stop	('F#5')
play	('G-5')
stop	('D-5', pause=True)
stop	('G-5')
play	('F#5')
play	('A-4')
stop	('F#5', pause=True)
play	('D-5')
stop	('A-4', pause=True)
stop	('D-5')
play	('C-5')
play	('E-5')
pause	(24)
stop	('C-5')
stop	('E-5')
play	('G-4')
play	('B-4')
stop	('G-4', pause=True)
stop	('B-4')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
play	('E-5')
play	('G-5')
stop	('E-5', pause=True)
stop	('G-5')
play	('E-4')
vol_range	(3)
play	('F#5')
pause	(3)
stop	('E-4')
vol_range	(1)
play	('F-4')
stop	('F-4', pause=True)
play	('F#4')
stop	('F#4', pause=True)
play	('G-4')
stop	('G-4', pause=True)
vol_range	(2)
play	('G#4')
stop	('G#4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D#5')
stop	('D#5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
stop	('F#5', pause=True)
vol_range	(3)
play	('G-5')
stop	('G-5', pause=True)
play	('G#5')
stop	('G#5', pause=True)
play	('F#5')
vol_range	(2)
play	('A-5')
pause	(12)
stop	('F#5')
stop	('A-5')
vol_range	(3)
play	('E-5')
vol_range	(2)
play	('G-5')
stop	('E-5', pause=True)
stop	('G-5')
vol_range	(3)
play	('D-5')
vol_range	(2)
play	('F#5')
stop	('D-5', pause=True)
stop	('F#5')
play	('C-5')
play	('E-5')
stop	('C-5', pause=True)
stop	('E-5')
inst	(0x5)
c6(0x7)
volume	(100)
pause	(24)
vol_range	(3)
play	('B-5')
play	('D-6')
pause	(6)
stop	('B-5')
stop	('D-6')
pause	(18)
vol_range	(2)
play	('B-5')
play	('D-6')
stop	('B-5', pause=True)
stop	('D-6')
vol_range	(3)
play	('B-5')
play	('D-6')
pause	(6)
stop	('B-5')
stop	('D-6')
pause	(32)
pause	(16)
play	('A-5')
play	('D-6')
pause	(6)
stop	('A-5')
stop	('D-6')
pause	(18)
vol_range	(2)
play	('A-5')
play	('D-6')
stop	('A-5', pause=True)
stop	('D-6')
vol_range	(3)
play	('A-5')
play	('D-6')
pause	(6)
stop	('A-5')
stop	('D-6')
pause	(32)
pause	(4)
play	('C-6')
play	('E-6')
pause	(6)
stop	('C-6')
stop	('E-6')
pause	(6)
play	('C-6')
play	('E-6')
stop	('C-6', pause=True)
stop	('E-6')
pause	(18)
play	('C-6')
play	('E-6')
stop	('C-6', pause=True)
stop	('E-6')
play	('C-6')
play	('E-6')
pause	(6)
stop	('C-6')
stop	('E-6')
pause	(12)
play	('C-6')
play	('E-6')
pause	(6)
stop	('C-6')
stop	('E-6')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('E-6')
stop	('E-6', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('A-5')
play	('E-6')
stop	('A-5', pause=True)
stop	('E-6')
pause	(6)
play	('B-5')
play	('D#6')
stop	('B-5', pause=True)
stop	('D#6')
play	('C-6')
play	('E-6')
stop	('C-6', pause=True)
stop	('E-6')
play	('E-6')
play	('G-6')
stop	('E-6', pause=True)
stop	('G-6')
pause	(6)
play	('C-6')
play	('E-6')
stop	('C-6', pause=True)
stop	('E-6')
play	('D-6')
play	('F#6')
stop	('D-6', pause=True)
stop	('F#6')
play	('E-6')
play	('G-6')
stop	('E-6', pause=True)
stop	('G-6')
play	('A-5')
play	('F#6')
stop	('A-5', pause=True)
stop	('F#6')
play	('B-5')
play	('E-6')
stop	('B-5', pause=True)
stop	('E-6')
play	('F#6')
play	('D-6')
stop	('F#6', pause=True)
stop	('D-6')
halt	()
halt	()
compress()
