nop()
track	(0x6)
inst	(0x5)
c6(0xa)
c6(0x7)
pan	(40)
volume	(95)
pause	(12)
vol_range	(2)
play	('D-6', far=True)
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
vol_range	(3)
play	('D-6')
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
vol_range	(2)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
vol_range	(3)
play	('D-6')
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
vol_range	(2)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
play	('D-6')
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(9)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(32)
pause	(1)
vol_range	(2)
play	('D-6')
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
vol_range	(3)
play	('D-6')
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
vol_range	(2)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
vol_range	(3)
play	('D-6')
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
vol_range	(2)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
play	('D-6')
play	('C-6')
pause	(3)
stop	('D-6')
stop	('C-6')
pause	(3)
play	('D-6')
play	('C-6')
stop	('D-6', pause=True)
stop	('C-6')
pause	(15)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
play	('C-6')
play	('A#5')
pause	(3)
stop	('C-6')
stop	('A#5')
pause	(3)
play	('C-6')
play	('A#5')
stop	('C-6', pause=True)
stop	('A#5')
pause	(15)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('G-5')
stop	('A-5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(9)
play	('A-5')
play	('G-5')
pause	(3)
stop	('A-5')
stop	('G-5')
pause	(32)
pause	(1)
vol_range	(2)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
play	('A-5')
play	('E-5')
pause	(3)
stop	('A-5')
stop	('E-5')
pause	(3)
play	('A-5')
play	('E-5')
stop	('A-5', pause=True)
stop	('E-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('E-5')
pause	(3)
stop	('A-5')
stop	('E-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('E-5')
stop	('A-5', pause=True)
stop	('E-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('F-5')
pause	(3)
stop	('A-5')
stop	('F-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('F-5')
stop	('A-5', pause=True)
stop	('F-5')
pause	(15)
play	('A-5')
play	('F-5')
pause	(3)
stop	('A-5')
stop	('F-5')
pause	(3)
play	('A-5')
play	('F-5')
stop	('A-5', pause=True)
stop	('F-5')
pause	(15)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('D#5')
pause	(3)
stop	('A-5')
stop	('D#5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('D#5')
stop	('A-5', pause=True)
stop	('D#5')
pause	(15)
play	('A-5')
play	('E-5')
pause	(3)
stop	('A-5')
stop	('E-5')
pause	(3)
play	('A-5')
play	('E-5')
stop	('A-5', pause=True)
stop	('E-5')
pause	(15)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
vol_range	(3)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
vol_range	(2)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
play	('C-6')
play	('A-5')
pause	(3)
stop	('C-6')
stop	('A-5')
pause	(3)
play	('C-6')
play	('A-5')
stop	('C-6', pause=True)
stop	('A-5')
pause	(15)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
vol_range	(3)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
vol_range	(2)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
play	('A#5')
play	('G-5')
pause	(3)
stop	('A#5')
stop	('G-5')
pause	(3)
play	('A#5')
play	('G-5')
stop	('A#5', pause=True)
stop	('G-5')
pause	(15)
play	('A-5')
play	('E-5')
pause	(3)
stop	('A-5')
stop	('E-5')
pause	(3)
play	('A-5')
play	('E-5')
stop	('A-5', pause=True)
stop	('E-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('E-5')
pause	(3)
stop	('A-5')
stop	('E-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('E-5')
stop	('A-5', pause=True)
stop	('E-5')
pause	(15)
vol_range	(3)
play	('A-5')
play	('F-5')
pause	(3)
stop	('A-5')
stop	('F-5')
pause	(3)
vol_range	(2)
play	('A-5')
play	('F-5')
stop	('A-5', pause=True)
stop	('F-5')
pause	(15)
play	('A-5')
play	('F-5')
pause	(3)
stop	('A-5')
stop	('F-5')
pause	(3)
play	('A-5')
play	('F-5')
stop	('A-5', pause=True)
stop	('F-5')
pause	(3)
play	('A-5')
play	('A-3', far=True)
stop	('A-3', pause=True)
set_note('A-5', pause=True)
play	('A-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('A-5', pause=True)
play	('A-6')
stop	('A-6', pause=6)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('G-6')
stop	('G-6', pause=6)
play	('A-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('A-5', pause=True)
play	('F#6')
stop	('F#6', pause=6)
play	('G-6')
play	('A-3', far=True)
stop	('A-3', pause=True)
set_note('G-6', pause=True)
play	('A-6')
play	('A-4', far=True)
stop	('A-4', pause=True)
set_note('A-6', pause=True)
play	('A-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('A-5', pause=True)
play	('G-6')
play	('A-5')
stop	('A-5', pause=True)
stop	('G-6', pause=True)
play	('A-6')
stop	('A-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('E-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('E-5', pause=True)
play	('A-4')
play	('A-3')
stop	('A-3', pause=True)
stop	('A-4', pause=True)
pause	(6)
vol_range	(3)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
vol_range	(2)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('E-6')
play	('C-6')
pause	(12)
stop	('E-6')
stop	('C-6')
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
vol_range	(2)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
play	('D-6')
play	('A#5')
pause	(12)
stop	('D-6')
stop	('A#5')
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(2)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('B-5')
play	('G-5')
pause	(12)
stop	('B-5')
stop	('G-5')
play	('C#5')
stop	('C#5', pause=6)
pause	(6)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(2)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
pause	(18)
vol_range	(3)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(2)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('E-6')
play	('C-6')
pause	(12)
stop	('E-6')
stop	('C-6')
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
vol_range	(2)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
play	('D-6')
play	('A#5')
pause	(12)
stop	('D-6')
stop	('A#5')
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(2)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('B-5')
play	('G-5')
pause	(12)
stop	('B-5')
stop	('G-5')
play	('C#5')
stop	('C#5', pause=6)
pause	(6)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(2)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
pause	(18)
vol_range	(3)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(2)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('E-6')
play	('C-6')
pause	(12)
stop	('E-6')
stop	('C-6')
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
vol_range	(2)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
play	('D-6')
play	('A#5')
pause	(12)
stop	('D-6')
stop	('A#5')
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(2)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('B-5')
play	('G-5')
pause	(12)
stop	('B-5')
stop	('G-5')
play	('C#5')
stop	('C#5', pause=6)
pause	(6)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(2)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
pause	(18)
vol_range	(3)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(2)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('E-6')
play	('C-6')
stop	('E-6', pause=True)
stop	('C-6')
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('E-6')
play	('C-6')
pause	(12)
stop	('E-6')
stop	('C-6')
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
vol_range	(3)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
vol_range	(2)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('D-6')
play	('A#5')
stop	('D-6', pause=True)
stop	('A#5')
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
play	('D-6')
play	('A#5')
pause	(12)
stop	('D-6')
stop	('A#5')
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
vol_range	(3)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
vol_range	(2)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
pause	(6)
play	('B-5')
play	('G-5')
stop	('B-5', pause=True)
stop	('G-5')
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('B-5')
play	('G-5')
pause	(12)
stop	('B-5')
stop	('G-5')
play	('C#5')
stop	('C#5', pause=6)
pause	(6)
play	('A-5')
play	('A-3', far=True)
stop	('A-3', pause=3)
pause	(3)
stop	('A-5', far=True)
play	('A-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('A-5', pause=True)
play	('A-6')
stop	('A-6', pause=6)
play	('A-5')
stop	('A-5', pause=True)
pause	(3)
play	('G-6')
stop	('G-6', pause=6)
play	('A-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('A-5', pause=True)
play	('F#6')
stop	('F#6', pause=6)
play	('G-6')
play	('A-3', far=True)
stop	('A-3', pause=True)
set_note('G-6', pause=True)
play	('A-6')
play	('A-4', far=True)
stop	('A-4', pause=True)
set_note('A-6', pause=True)
play	('A-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('A-5', pause=True)
play	('G-6')
play	('A-5')
stop	('A-5', pause=True)
stop	('G-6', pause=True)
play	('A-6')
stop	('A-6', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('E-5')
play	('A-4')
stop	('A-4', pause=True)
stop	('E-5', pause=True)
play	('A-4')
play	('A-3')
stop	('A-3', pause=True)
stop	('A-4', pause=True)
halt	()
halt	()
compress()
