nop()
track	(0x3)
inst	(0x4)
c6(0xa)
c6(0x7)
pan	(80)
volume	(85)
vol_range	(3)
play	('C-6', far=True)
stop	('C-6', pause=6)
pause	(18)
play	('E-6')
stop	('E-6', pause=6)
pause	(18)
play	('A-5')
pause	(32)
stop	('A-5', pause=16)
pause	(12)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('E-5')
pause	(32)
pause	(32)
pause	(32)
stop	('E-5', pause=3)
pause	(32)
pause	(13)
play	('C-6')
stop	('C-6', pause=6)
pause	(18)
play	('E-6')
stop	('E-6', pause=6)
pause	(18)
play	('A-5')
pause	(32)
stop	('A-5', pause=16)
pause	(12)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('E-5')
pause	(32)
pause	(32)
pause	(32)
stop	('E-5', pause=18)
vol_range	(2)
play	('F-5')
stop	('F-5', pause=3)
play	('F#5')
stop	('F#5', pause=3)
vol_range	(3)
play	('G-5')
stop	('G-5', pause=12)
play	('A-5')
stop	('A-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(18)
play	('E-6')
stop	('E-6', pause=6)
pause	(18)
play	('A-5')
pause	(32)
stop	('A-5', pause=16)
pause	(12)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=4)
play	('C-6')
stop	('C-6', pause=4)
play	('A-5')
stop	('A-5', pause=4)
play	('E-5')
stop	('E-5', pause=True)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('E-5')
pause	(32)
pause	(32)
pause	(32)
stop	('E-5', pause=18)
vol_range	(2)
play	('F-5')
stop	('F-5', pause=3)
play	('F#5')
stop	('F#5', pause=3)
vol_range	(3)
play	('G-5')
stop	('G-5', pause=12)
play	('A-5')
stop	('A-5', pause=12)
play	('C-6')
stop	('C-6', pause=6)
pause	(18)
play	('E-6')
stop	('E-6', pause=6)
pause	(18)
play	('A-5')
pause	(32)
stop	('A-5', pause=16)
pause	(12)
play	('C-6')
stop	('C-6', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('A-5')
stop	('A-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
play	('G-5')
stop	('G-5', pause=6)
pause	(18)
play	('E-5')
pause	(32)
stop	('E-5', pause=16)
pause	(32)
pause	(32)
pause	(32)
inst	(0x0)
c6(0x7)
volume	(80)
vol_range	(2)
play	('E-5')
stop	('E-5', pause=6)
pause	(12)
play	('E-5')
stop	('E-5', pause=6)
pause	(12)
play	('E-5')
stop	('E-5', pause=6)
pause	(18)
vol_range	(1)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
pause	(18)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
pause	(12)
play	('D-5')
stop	('D-5', pause=6)
pause	(12)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
vol_range	(1)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
pause	(18)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(18)
vol_range	(1)
play	('B-4')
stop	('B-4', pause=6)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(18)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(18)
vol_range	(1)
play	('B-4')
stop	('B-4', pause=6)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(18)
vol_range	(2)
play	('E-5')
stop	('E-5', pause=6)
pause	(12)
play	('E-5')
stop	('E-5', pause=6)
pause	(12)
play	('E-5')
stop	('E-5', pause=6)
pause	(18)
vol_range	(1)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('E-5')
stop	('E-5', pause=True)
pause	(18)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=6)
pause	(12)
play	('D-5')
stop	('D-5', pause=6)
pause	(12)
play	('D-5')
stop	('D-5', pause=6)
pause	(18)
vol_range	(1)
play	('D-5')
stop	('D-5', pause=6)
pause	(6)
play	('D-5')
stop	('D-5', pause=True)
pause	(18)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(18)
vol_range	(1)
play	('B-4')
stop	('B-4', pause=6)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(18)
vol_range	(2)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(12)
play	('B-4')
stop	('B-4', pause=6)
pause	(18)
vol_range	(1)
play	('B-4')
stop	('B-4', pause=6)
pause	(6)
play	('B-4')
stop	('B-4', pause=True)
pause	(18)
inst	(0x4)
c6(0x7)
volume	(85)
pause	(6)
vol_range	(2)
play	('D-5')
stop	('D-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
vol_range	(3)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=3)
play	('F-5')
stop	('F-5', pause=3)
play	('E-5')
stop	('E-5', pause=3)
play	('D#5')
stop	('D#5', pause=3)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
vol_range	(3)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
vol_range	(2)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
halt	()
halt	()
compress()
