nop()
track	(0x1)
inst	(0x2)
c6(0x7)
volume	(70)
vol_range	(3)
play	('D-5', far=True)
pause	(6)
play	('D-5')
stop	('D-5')
stop	('D-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(30)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('A#5')
stop	('A#5', pause=6)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
play	('G-6')
stop	('G-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-6')
stop	('F-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
pause	(6)
play	('F-6')
stop	('F-6', pause=True)
pause	(6)
play	('F-5')
stop	('F-5', pause=True)
pause	(18)
play	('E-5')
stop	('E-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('E-6')
stop	('E-6', pause=6)
play	('E-5')
stop	('E-5', pause=6)
play	('B-5')
stop	('B-5', pause=6)
pause	(6)
play	('E-6')
stop	('E-6', pause=True)
play	('E-5')
stop	('E-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C#5')
stop	('C#5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('D-6')
stop	('D-6', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('G-5')
stop	('G-5', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('G-6')
stop	('G-6', pause=6)
play	('G-5')
stop	('G-5', pause=6)
play	('A#5')
stop	('A#5', pause=6)
pause	(6)
play	('D-6')
stop	('D-6', pause=True)
play	('G-6')
stop	('G-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('D-5')
stop	('D-5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('F-5')
stop	('F-5', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('F-6')
stop	('F-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
play	('C-6')
stop	('C-6', pause=True)
play	('F-5')
stop	('F-5', pause=True)
pause	(6)
play	('F-6')
stop	('F-6', pause=True)
pause	(6)
play	('F-5')
stop	('F-5', pause=True)
pause	(32)
pause	(32)
pause	(32)
pause	(18)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('A-4')
stop	('A-4', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('A-5')
stop	('A-5', pause=6)
play	('A-4')
stop	('A-4', pause=6)
play	('G-5')
stop	('G-5', pause=6)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(18)
play	('D-5')
stop	('D-5', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('D-6')
stop	('D-6', pause=6)
play	('D-5')
stop	('D-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('B-5')
stop	('B-5', pause=True)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('C-6')
stop	('C-6', pause=True)
pause	(6)
play	('B-5')
stop	('B-5', pause=True)
pause	(18)
play	('C-5')
stop	('C-5', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('C-6')
stop	('C-6', pause=6)
play	('C-5')
stop	('C-5', pause=6)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('A#5')
stop	('A#5', pause=True)
play	('C-5')
stop	('C-5', pause=True)
play	('B-4')
stop	('B-4', pause=True)
play	('C-5')
stop	('C-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('A-5')
stop	('A-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
play	('G-5')
stop	('G-5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
pause	(32)
pause	(32)
pause	(32)
pause	(6)
play	('F#5')
stop	('F#5', pause=3)
play	('F-5')
stop	('F-5', pause=3)
play	('E-5')
stop	('E-5', pause=3)
play	('D#5')
stop	('D#5', pause=3)
halt	()
halt	()
compress()
