nop()
track	(0x9)
inst	(0x3)
c6(0x7)
volume	(90)
vol_range	(3)
play	('C-3', far=True)
pause	(12)
vol_range	(2)
play	('A-8', far=True)
stop	('C-3', far=True)
pause	(6)
stop	('A-8', far=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('C-3')
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('C-3')
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('C-3')
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('C-3')
pause	(32)
stop	('C-3', pause=4)
play	('C-3')
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=6)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('C-3')
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=6)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('C-3')
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(3)
play	('A-8')
stop	('A-8', pause=6)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('C-3')
stop	('C-3', pause=12)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=12)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('A#4', far=True)
stop	('A#4', pause=12)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
play	('C-3', far=True)
stop	('C-3', pause=12)
pause	(32)
pause	(32)
pause	(8)
play	('A#4', far=True)
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
play	('C-3', far=True)
stop	('C-3', pause=6)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=6)
play	('A-8')
stop	('A-8', pause=6)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=6)
play	('A#4', far=True)
stop	('A#4', pause=6)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('C-3')
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(2)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
play	('A-8')
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
pause	(6)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
vol_range	(2)
play	('A-8', far=True)
stop	('A-8', pause=True)
vol_range	(3)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=True)
play	('A#4', far=True)
stop	('A#4', pause=True)
play	('A#4')
stop	('A#4', pause=True)
play	('C-3', far=True)
stop	('C-3', pause=12)
pause	(32)
pause	(32)
pause	(8)
play	('A#4', far=True)
stop	('A#4', pause=6)
play	('A#4')
stop	('A#4', pause=6)
c6(0x6)
song	(3)
halt	()
halt	()
compress()
