nop()
track	(0x2)
inst	(0x4)
c6(0x7)
volume	(85)
vol_range	(3)
play	('A-3', far=True)
stop	('A-3', pause=12)
play	('A-3')
stop	('A-3', pause=12)
play	('A-4')
stop	('A-4', pause=12)
play	('A-3')
stop	('A-3', pause=12)
play	('C#4')
stop	('C#4', pause=6)
pause	(18)
play	('E-4')
stop	('E-4', pause=6)
pause	(6)
play	('F#4')
stop	('F#4', pause=True)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
pause	(12)
play	('G-4')
stop	('G-4', pause=6)
play	('F#4')
stop	('F#4', pause=6)
pause	(6)
play	('G-4')
stop	('G-4', pause=True)
pause	(6)
play	('A-4')
stop	('A-4', pause=True)
play	('E-4')
stop	('E-4', pause=True)
pause	(6)
play	('C#4')
stop	('C#4', pause=True)
play	('A-3')
stop	('A-3', pause=True)
pause	(18)
c6(0x6)
song	(5)
halt	()
halt	()
