nop()
inst	(0x0)
c6(0x7)
volume	(80)
vol_range	(3)
play	('A-4', far=True)
stop	('A-4', pause=12)
play	('A-4')
stop	('A-4', pause=12)
play	('A-5')
stop	('A-5', pause=12)
play	('A-4')
stop	('A-4', pause=12)
play	('C#5')
stop	('C#5', pause=6)
pause	(18)
play	('E-5')
stop	('E-5', pause=6)
pause	(6)
play	('F#5')
stop	('F#5', pause=True)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
pause	(12)
play	('G-5')
stop	('G-5', pause=6)
play	('F#5')
stop	('F#5', pause=6)
pause	(6)
play	('G-5')
stop	('G-5', pause=True)
pause	(6)
play	('A-5')
stop	('A-5', pause=True)
play	('E-5')
stop	('E-5', pause=True)
pause	(6)
play	('C#5')
stop	('C#5', pause=True)
play	('A-4')
stop	('A-4', pause=True)
halt	()
halt	()
